### ISSUE TITLE
Remove SSLv2/v3 support

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#101]
For security reasons, can you remove SSLv2/v3 support of Psi?

Windows XP (which out in 2001, 13 years) has TLS 1.0 support (and a little note: the ending support will be stopped in some months).

Thanks in advance for users security.

**Comment by Neustradamus** [comment]
XEP-0368: SRV records for XMPP over TLS
https://xmpp.org/extensions/xep-0368.html

**Comment by Ri0n** [comment]
doesn't make much sense to me. If a used connect to some old server based on old protocols. should we reject the connection?
I'd rather say it's up to server to restrict protocols. 
And in any case those protocols are not used nowadays
