### ISSUE TITLE
Impossible to choose spell check language

### ISSUE THREAD

**Issue by fpiecka** [psi-im/psi#114]
Psi uses the default language from aspell configuration. However people often use a different language for different programs and sometimes it is impractical to set the default systemwide.

It would be beneficial to add support for spell check language selection to options.

A possibility to change language via right click in the messaging window would be even better...

**Comment by GreenLunar** [comment]
> Try set language with environment variable LANG

Do you mean `$ LANG=xx_XX.utf8 psi`?

I use *Psi 0.15* on *Salix 14.1*.  Psi properly indicates on spelling mistakes in English but does not in Hebrew; in Hebrew, Psi always indicates that word is misspelled.

Related: #43

**Comment by GreenLunar** [comment]
Executing `$ LANG=he_IL.utf8 psi` makes Psi to use Hebrew spell checker but Psi fails to use English spell checker.

**Comment by GreenLunar** [comment]
[Psi spell-checking for multiple languages](http://endl.ch/content/psi-spell-checking-multiple-languages)

Simple patch for Psi 0.11-0.13 which adds support for multiple languages in its spell-checking engine.

**Comment by GreenLunar** [comment]
@ndl PING!

Please join to this thread.

**Comment by ndl** [comment]
Hi, 

I've switched to Vacuum (http://www.vacuum-im.org/) quite some time ago
and, therefore, do not follow Psi development anymore - hence don't have
corresponding patches for any of the recent versions of Psi. Sorry about
that :-( 

IIRC there was not that much code involved, though, so porting /
re-implementing them shouldn't be very difficult. 

On 2015-09-16 13:41, GreenLunar wrote: 

> @ndl [1] PING! 
> 
> Please join to this thread. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Good luck! Alexander
 

Links:
------
[1] https://github.com/ndl
[2] https://github.com/psi-im/psi/issues/114#issuecomment-140715462

**Comment by GreenLunar** [comment]
Does Vacuum have a spell checker as described?

**Comment by wadealer** [comment]
GreenLunar, we already have this patches at psi-plus. One day psi will has it to :)

**Comment by The-Judge** [comment]
Sorry for writing to such an old thread again; I'm using psi-plus (v0.16.330) and I cannot choose from several / multiple languages. I can only (de-)activate spell checking.
Have these patches become removed again?

**Comment by tehnick** [comment]
@The-Judge It is recommended to use the latest available release of Psi+: 1.2.100.
See https://github.com/psi-plus/main/issues/695 for details.

**Comment by tehnick** [comment]
@Ri0n Is it time to move these patches to Psi? They are well tested.

**Comment by tehnick** [comment]
@The-Judge As for old Psi and Psi+ versions you may try to choose languages in advanced settings:

Settings dialog --> Advanced --> options --> ui --> spell-check --> langs (use short language names and comma as a separator, for example "ru,en")

As far as I remember if you build Psi/Psi+ with aspell you may choose only two dictionaries simultaneously. With hunspell you may use more than 2 languages, but there were a bug (see link above).

**Comment by Ri0n** [comment]
@tehnick, sure. we should apply them

**Comment by The-Judge** [comment]
Cool, thanks for the input!
It works for me now with the latest version!

**Comment by tehnick** [comment]
bfbee1138e8ff551537f465addacd469d3101279
