### ISSUE TITLE
There is not history for room@conference.example.tld/user

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#115]
Like subject: There is not history for room@conference.example.tld/user.

Linked to https://github.com/psi-plus/main/issues/643

-> Conference logger plugin "chat" part is missing, "groupchat" is ok

**Comment by Ri0n** [comment]
according to @liuch it's already implemented and not commited.

**Comment by Neustradamus** [comment]
Yes, only in the SQL datebase not in a text file badly.
