### ISSUE TITLE
XEPs and RFCs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#120]
Dear @psi-im team, @psi-plus team, @Ri0n, @Vitozz, @tehnick,

It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

Thanks in advance.

**Comment by stevenroose** [comment]
I came here while looking for a XEP list. Seems to still not exist.

**Comment by tehnick** [comment]
https://github.com/psi-im/psi/wiki/Supported-XEPs

**Comment by Neustradamus** [comment]
@tehnick: Thanks but supported XEP versions are missing and RFC in the same time ^^

**Comment by Neustradamus** [comment]
A new XEP has been added: https://github.com/psi-im/psi/issues/259

Hope the XEP in this document with the VERSION and RFCs too

**Comment by Neustradamus** [comment]
Currently there are only, the previous list is false...
- Ad-Hoc Commands (XEP-0050)
- Bits of Binary (XEP-0231)
- Chat State Notifications (XEP-0085)
- Data Forms (XEP-0004)
- Entity Time (XEP-0202)
- File Transfer (XEP-0096)
- In-Band Bytestreams (XEP-0047)
- Jingle (XEP-0166)
- Last Message Correction (XEP-0308)
- Message Receipts (XEP-0184)
- Multi-User Chat (XEP-0045)
- Roster Item Exchange (XEP-0144)
- SI File Transfer (XEP-0096)
- SOCKS5 Bytestreams (XEP-0065)
- Service Discovery Info (XEP-0030)
- User Activity (XEP-0108)
- User Avatars (XEP-0084)
- User Avatars and notify (XEP-0084)
- User Geolocation (XEP-0080)
- User Mood (XEP-0107)
- User activity and notify (XEP-0108)
- User mood and notify (XEP-0107)
- User tune (XEP-0118)
- Whiteboard (XEP-XXXX)
- XHTML-IM (XEP-0071)
- XMPP Ping (XEP-0199)
- http://jabber.org/protocol/sxe
- Неизвестная фича: eu.siacs.conversations.axolotl.devicelist+notify
- Неизвестная фича: urn:xmpp:hash-function-text-names:blake2b-256
- Неизвестная фича: urn:xmpp:hash-function-text-names:blake2b-512
- Неизвестная фича: urn:xmpp:hash-function-text-names:sha-1
- Неизвестная фича: urn:xmpp:hash-function-text-names:sha-256
- Неизвестная фича: urn:xmpp:hash-function-text-names:sha-512
- Неизвестная фича: urn:xmpp:hash-function-text-names:sha3-256
- Неизвестная фича: urn:xmpp:hash-function-text-names:sha3-512
- Неизвестная фича: urn:xmpp:jingle:apps:file-transfer:5
- Неизвестная фича: urn:xmpp:jingle:transports:ibb:1
- Неизвестная фича: urn:xmpp:jingle:transports:s5b:1
Категория: client | Тип: pc | Название: Psi+
ПО: Psi+ | Версия: 1.4.1303 (2020-05-27, Psi:f34443ba, Psi+:2170e90)

**Comment by Ri0n** [comment]
Neustradamus, you are wrong
