### ISSUE TITLE
Jitsi users have ICQ icon

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#121]
A little bug, jitsi users have an ICQ icon.
![bug1](https://f.cloud.github.com/assets/104737/2181335/fb9f5cf4-974b-11e3-97fe-f78a11b8c9ad.png)

**Comment by Neustradamus** [comment]
In May 2018, Jitsi is missing in \iconsets\clients\default ^^

**Comment by Neustradamus** [comment]
Any news, 5 years after?
- https://i.ibb.co/4YnM5CW/psi-plus-icq-icon-jitsi-1.png
- https://i.ibb.co/D7jSR8B/psi-plus-icq-icon-jitsi-2.png

**Comment by Ri0n** [comment]
Jit - jabber icq transport. I believe it's still valid

**Comment by Ri0n** [comment]
Or not.. I heard they changed their protocol totally incompatible way. So probably we can discard this jit regexp since icq is also kind of abandoned in xmpp world

**Comment by Neustradamus** [comment]
@ri0n: Can you reopen this ticket?

**Comment by Neustradamus** [comment]
@tehnick, @Ri0n, @Vitozz: Always here in 2020 ;)
Time to look?

**Comment by Ri0n** [comment]
seems like it's time to get rid of icq completely

**Comment by Ri0n** [comment]
I believe I cleaned up everything carefully
