### ISSUE TITLE
Wiki Unavailable

### ISSUE THREAD

**Issue by RoyCLee** [psi-im/psi#125]
When I go to http://psi-im.org/wiki/User_Guide, I get the message:
A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT lc_value FROM `mw_l10n_cache` WHERE lc_lang = 'en' AND lc_key = 'deps' LIMIT 1
Function: LCStore_DB::get
Error: 1146 Table 'psi_im_org.mw_l10n_cache' doesn't exist (mysql.psi-im.org)

When I go to http://psi-im.org/wiki. I get the message:
A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT value,exptime FROM `mw_objectcache` WHERE keyname = 'psi_im_org-mw_:messages:en' LIMIT 1
Function: SqlBagOStuff::get
Error: 1146 Table 'psi_im_org.mw_objectcache' doesn't exist (mysql.psi-im.org)

**Comment by nunom** [comment]
This still happens. If you're going to drop that wiki then do it, put a 404 placeholder instead.
Otherwise this leaves the impression Psi is dead (is it? no news since 2012)
