### ISSUE TITLE
One minute connection delay on IPv4 Windows clients with IPv6 server

### ISSUE THREAD

**Issue by aef** [psi-im/psi#140]
Users of Psi always have to wait almost exactly one minute until they are connected to my server. After trying to track this back, I realized that this started immediately after offering IPv6 on our server. Meaning that the domain name the SRV record for client connections points to has an AAAA DNS record.

The problem occurs only on Windows machines that have no public IPv6 address and can be circumvented by setting the IPv4 address of the server manually in the account options. It seems, even though there is no public IPv6 address available, Psi tries to connect to it somehow and spends 60 seconds doing that before trying the IPv4 address.

Just for reference, my users use Psi 0.15 on Windows 7 and 8 and we are running a Prosody 0.9.4 server.

**Comment by Neustradamus** [comment]
@aef There are changes since 2014?
Have you tested with a new 1.4.x Psi or Psi+ version?

**Comment by Ri0n** [comment]
rfc6555 was implemented in Psi long ago
