### ISSUE TITLE
STUN seems not working for filetransfer

### ISSUE THREAD

**Issue by beelze** [psi-im/psi#152]
I've tried to send files out-of-band but with no success (in-band and proxy turned off, tried different STUN servers). XMPP console shows that my side provided only «local» IP (interface binded):

streamhost port="8010" host="192.168.11.xx" jid="myjid@domain.tld/Psi"/

of course, receiving side is unable to connect to internal address 192.168.11.xx:8010. More, tshark shows that no packets was even sent to choosed STUN server host.

For the comparison, same settings (STUN with no proxy) in Pidgin produced 2 «streamhosts» – with local and public IPs and client is able to send file.

**Comment by Ri0n** [comment]
Unfortunately it won't be implemented for 2.0. It requires implementation of Jingle ICE transport. And for file transport we need datachannels over DTLS which was added to Qt starting from 5.12 iirc.
2.0 will be released with Qt 5.5 support. Then likely 2.1 with Qt 5.9.
If I find some other solution I'll try to add SCTP+DTLS transport for file transfer for Psi 2.1. Both STUN and TURN will be supported but I can't postpone 2.0 release that long.

**Comment by Ri0n** [comment]
it's supported now.
