### ISSUE TITLE
Psi doesn't work after upgrading to ubuntu 14.10

### ISSUE THREAD

**Issue by mmgomess** [psi-im/psi#167]
After upgrading my ubuntu to 14.10 I've encounter problem with psi. Psi displays warning:

Unable to bind to port 8010 for Data Transfer.
This may mean you are already running another instance of Psi.
You may experienceproblems sending and/or receiving files.
And than crashes. Does someone encounter same or similar problem and could give me advice how to cope with it?

There is no other instance of psi running and nothing blocks this port. I also tried to change port in configuration file.

**Comment by Ri0n** [comment]
show "netstat -ltpn" output. sounds strange anyway

**Comment by Ri0n** [comment]
No response
