### ISSUE TITLE
Notification sound disorted

### ISSUE THREAD

**Issue by mkkot** [psi-im/psi#170]
Hello,

please go to https://github.com/psi-im/psi/tree/master/sound and listen to notification waves. They are loud disorted moans which made me think that there is something wrong with pulseaudio or sound card. I have checked them on mplayer, xine and vlc, effect is the same. My system is able to play other waves properly.
I'm wondering how that happened since these waves seem to be untouched for 8 years on github...

**Comment by Ri0n** [comment]
checked sounds again with pipewire this time on another laptop. still sound good.
I believe there was something wrong with your system.
