### ISSUE TITLE
Status messages are clipped off when displayed in a separate line

### ISSUE THREAD

**Issue by FlorianFieber** [psi-im/psi#171]
With the settings given below, the lower part of a status message is clipped off in the roster (see the attached screenshot). This is a regression introduced with 5e2dd5c6c7b33e89ad31b79e89d7ccbf737bbb9d.

![statusmessage_cut_off](https://cloud.githubusercontent.com/assets/917394/6006325/e9c06c1e-ab11-11e4-8afb-b00247b5dc49.png)

Steps to reproduce:
1. Set `options.ui.contactlist.status-messages.show` to `true`
2. Set `options.ui.contactlist.status-messages.single-line` to `false`
3. Increase the font size of the roster. For me, this starts with DejaVu Sans 10.

Bonus bug (not a regression): With bigger font sizes, there isn't enough space allocated for the status message – here's a screenshot with Psi 09d3cf5:
![statusmessage_cut_off_2](https://cloud.githubusercontent.com/assets/917394/6006780/6fcaf646-ab15-11e4-8405-8d31b11619b3.png)

For me, this happens with DejaVu Sans >=11.

**Comment by FlorianFieber** [comment]
Another bug which I assume is based on the same regression: Some account names are truncated although there's enough space. Here's an example, "Account for Tests" with DejaVu Sans 10:

![account_name_truncated](https://cloud.githubusercontent.com/assets/917394/7831269/6d5944e6-0455-11e5-945e-54e7aecf0bff.png)

**Comment by Ri0n** [comment]
I believe it's not valid anymore. 
roster was rewritten several times after that with special attention to fonts sizes and roster item geometry.
