### ISSUE TITLE
Psi sending CAPS extension with deprecated format

### ISSUE THREAD

**Issue by stucchi** [psi-im/psi#172]
Hello there, 
 
  every time I connect with Psi to my XMPP server I get, into the presence tag a caps tag like the one below

```
<presence from="admin@mydomain.net/Resource" to="admin@mydomain.net">
<priority>5</priority>
<c xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ext="ca cs ep-notify-2 html" ver="caps-b75d8d2b25"/>
</presence> 
```

This format, and in particular `ext` element, is deprecated, as indicated in the XEP-0115 documentation http://www.xmpp.org/extensions/xep-0115.html#protocol 

The optimal solutions would be:

* comply with the XEP indication using `hash` parameter
* to be able to disable the caps sending from UI, so that I get a plain vanilla presence tag

So that libraries getting this presence won't complain about the format

Regards,
  Luca

**Comment by wadealer** [comment]
caps 1.5 implemented.

**Comment by k--andrey** [comment]
Problem exists in latest (0.15) version on windows

**Comment by Ri0n** [comment]
@k--andrey,  wait for release.
