### ISSUE TITLE
OpenPGP encrypted MUC

### ISSUE THREAD

**Issue by PolynomialDivision** [psi-im/psi#174]
HI,
I'm using Conversations as XMPP-App for Android and Psi for my PC.
In Conversations it's possible to encrypt messages via PGP to the contacts in the chat room.
It is possible for Psi to decrypt this messages in a chat room but I can't send encrypted messages.
It would be a great feature to support encrypted Mutliuser Chatrooms.

https://github.com/siacs/Conversations

**Comment by tehnick** [comment]
@PolynomialDivision 
Why you closed this issue?
