### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by Nekotekina** [psi-im/psi#176]
Sorry for the question. I set up Qt 5.4.1 with MinGW 4.91 and tried to follow https://github.com/psi-im/psi/blob/master/doc/build-win.txt these instructions. Are they outdated, or I'm just missing something? I cannot find crypto_win.prf, for example.

I also tried these instructions: http://qt-project.org/forums/viewthread/26157
But on 7) Qt didn't recognize -DECM_MODULE_PATH option. It seems it built it though but I'm not sure what to do with it.

Attempt to build Psi says that "qjdnsshared.h" is not found. I know it's a wrong way to do it, but I cannot even find this file as well.

**Comment by wadealer** [comment]
Check this up https://github.com/psi-im/psi/tree/master/admin/build

**Comment by Ri0n** [comment]
The scripts above should be good enough for building. If not then open separate bug
