### ISSUE TITLE
Google Hangouts/Gtalk is it (still) supported?

### ISSUE THREAD

**Issue by mwozny123** [psi-im/psi#184]
Hi 

as on the Psi features page there's still entry about Google Talk.
http://psi-im.org/features/

on this page I've found a configuration gtalk for psi:
http://crunchbang.org/forums/viewtopic.php?id=3095
but it doesn't work.

My question's : as Google switched from Gtalk to Hangouts, is Google Hangouts supported by Psi?

Marcin

**Comment by wadealer** [comment]
Google is still supported. Just use default account settings.
