### ISSUE TITLE
[win32] Is there a win-installer file?

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#185]
After reading a comment by @crayxt at https://github.com/psi-im/psi-translations/issues/5#issuecomment-121914316, I am wondering if there is a win-installer (nsh or nsi) file for Psi.

**Comment by crayxt** [comment]
@GreenLunar I think I meant the opposite - there are already nsh files in Psi https://github.com/psi-im/win-installer/tree/master/src/lang the question is whether weblate supports this format of files ;))
