### ISSUE TITLE
Notification when message arrives

### ISSUE THREAD

**Issue by illes72zoli** [psi-im/psi#188]
Hi all,

I'm looking for solution to my problem. I use PSI on a working environment where I have no admin rights over Windows 7. I have to continuously watch 4 different chat rooms. If there is an incoming messages, I can not really see at a glance which chat room was active last. Sometimes I see the canvas of the window blinking, but as I have an old windows style, it is just barely visible.
Question: Is there any other type of notification (pop-up window) which is more visible? Perhaps different sounds for different chat rooms?

**Comment by wadealer** [comment]
At Popups settings tab there is option for enabling popup notifications for every muc message.
