### ISSUE TITLE
[Linux] Launch Psi on system startup

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#189]
/General/Options/Application
**☐ Launch on system start** (or) **☐ Launch on system startup**

When checked, file `psi-autostart.desktop` with the following entries be created in `~/.config/autostart/`

```
[Desktop Entry]
Categories=Network;InstantMessaging;Qt;
Exec=psi
Icon=psi
Name=Psi
GenericName=XMPP Client
Comment=Communicate over the XMPP network
Terminal=false
Type=Application
Version=1.1
```

You may use this comment `Comment=Start Psi Messenger`.

**Comment by rapgro** [comment]
See https://github.com/psi-im/psi/blob/master/psi.desktop
There you submitted your Hebrew translation. What's the difference?

**Comment by GreenLunar** [comment]
There is no difference.  Psi can create that desktop file into `$XDG_CONFIG_DIR/autostart/`

**Comment by GreenLunar** [comment]
This is a task for Desktop Environment utilities to handle.  See https://gitlab.com/dianara/dianara-dev/issues/23
