### ISSUE TITLE
Add ellipsis to some items

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#191]
The following list may not be complete.

##### Menu /General/
Add a Contact (also in content-menu of account row)
New Blank Message (also in content-menu of account row)
Service Discovery (also in content-menu of account row)
Join Groupchat
Account Setup
Options
Transfer Manager
Change Profile

##### Context menu of account
Add a Contact
Service Discovery
New Blank Message

##### Context menu of contact
Send Message
Open Chat Window
Send File
Rename
Remove
Assign Custom Picture
Assign OpenPGP Key

##### Context menu of group
Send Message to Group
Remove Group
Remove Group and Contacts

##### Psi: XMPP Accounts
Add
Modify
Remove

##### Psi: Manage Profiles
Add
Rename
Remove

`.` U+002E FULL STOP (x3)
`…` U+2026 HORIZONTAL ELLIPSIS

**Comment by GreenLunar** [comment]
##### Context menu of group
Send Message to Group
Remove Group
Remove Group and Contacts

**Comment by Ri0n** [comment]
But what for?

**Comment by GreenLunar** [comment]
To indicate that no immediate action be made.

Adding ellipsis is usually being added to button/menu items to indicate that a new screen will be added and action is not immediate.

**Comment by wadealer** [comment]
GreenLunar, please stop spam at bugtracker! Befor create any new issue discuss it with developoers at psi-dev@conference.jabber.ru

**Comment by GreenLunar** [comment]
@wadealer, first of all, I apologies for the flood of comments.

Ellipsis is not something new to propose, there are already items with ellipsis in Psi such as *&Modify Account...*.  Not having ellipsis where is needed causes inconsistency in UI.

**Comment by tehnick** [comment]
@GreenLunar, Have you thought about amount of extra work for translators? Unfortunately our translators are not very active and all these strings will be untranslated during long time.

**Comment by GreenLunar** [comment]
Yes, I though about it.  It is a problem.

**Comment by GreenLunar** [comment]
In anyway, this issue is valid.  Please reopen it.

**Comment by GreenLunar** [comment]
Issue #190 (string rename) has been fixed.  This is a good time to apply the suggested modifications above.

**Comment by Ri0n** [comment]
I don't see any good reason to add ellipsis everywhere. I'd rather removed existing.
