### ISSUE TITLE
Incorrect window title

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#197]
###### Group row

When selecting **Remove Group** a dialog with title **Remove Group** appears. (Good)

When selecting **Remove Group and Contacts** a dialog with title **Psi** appears. (Bad)

###### Contact row

When selecting **Remove** a dialog with title **Psi** appears. (Bad)

**Comment by Ri0n** [comment]
Pull request is very appreciated

**Comment by GreenLunar** [comment]
I do not know where to aim.

**Comment by wadealer** [comment]
FIxed
