### ISSUE TITLE
Problem with plasma 5 tray

### ISSUE THREAD

**Issue by marco44** [psi-im/psi#205]
Hi,

When using psi with plasma 5, the left click doesn't work anymore on the tray icon (nothing happens). The right click works though. That's a bit weird.

**Comment by tehnick** [comment]
Which version of program do you use?
Is it built with Qt 4.x or with Qt 5.x?

**Comment by marco44** [comment]
It's the default package for archlinux
QT4.8.7, psi 0.15-2. Plasma is 5.4.3.

Tell me if you want me to test against a git build, qt5, or whatever you need to help.

**Comment by marco44** [comment]
Gave a try to latest git version, with QT 5.5.1. Same problem.

**Comment by Vitozz** [comment]
Is the problem still relevant?

**Comment by marco44** [comment]
No idea
