### ISSUE TITLE
PSIDATADIR location in README is incorrect

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#211]
File: https://github.com/psi-im/psi/blob/master/certs/README

```
Default value of PSIDATADIR:
  Linux, MacOS X and other Unices
     ~/.psi/ 
```

For Linux and other Unices, I would assume it is `.local/share/psi/certs/`.  You might prefer to write `$PSIDATADIR/` as written on [Configuration File - PsiWiki](http://wayback.archive.org/web/20130316072425/http://psi-im.org/wiki/Configuration_File) and [SSL Certificates (QCA1) - PsiWiki](http://wayback.archive.org/web/20130127204620/http://psi-im.org/wiki/SSL_Certificates_%28QCA1%29#The_rootcert.xml_File).

**Comment by drizt** [comment]
I think README is incorrect

**Comment by GreenLunar** [comment]
Yes, this is what I meant to.  I have corrected the title.

**Comment by Vitozz** [comment]
I think we should close this ticket. There is more no such information in README.

**Comment by tehnick** [comment]
@Vitozz It is. Just click on link in bug description.

We should update that README for Psi IM + add info about Psi+ paths there.
