### ISSUE TITLE
Error: need Generate .prl files! at Debian Jessie

### ISSUE THREAD

**Issue by dhyannataraj** [psi-im/psi#216]
Hi!

I am trying to build current master on Debian Jessie (I found a bug and wanted to report it with newest source and backtrace)
But I can not do it, as ./configure says me "Error: need Generate .prl files!"

$ ./configure 
Configuring Psi ...
Verifying Qt 4 build environment ... ok
Checking for Qt >= 4.7.0 ... 4.8.6
Checking for LibIDN ... yes
Checking for QCA >= 2.0 ... yes
Checking for zlib ... yes
Checking for QJDns ... yes
Checking for QDBUS ... yes
Checking for the XScreenSaver extension ... yes
Checking for spellcheck engine ... enchant
Generating .prl files ... fail

Error: need Generate .prl files!

I've installed build-dep for stable psi package. So I hope all dependencies are met.

I do not know how to hack into this qt-building system of yours. Can you help me with this?

**Comment by Ri0n** [comment]
Did you try to start with --verbose?

**Comment by Ri0n** [comment]
no response

**Comment by antonte** [comment]
Looks like tools.pri grepshortcutkeydialog.pri iris.pri are missing

Generating .prl files ...
 * [/usr/lib64/qt4//bin/qmake-qt4 -prl -r ./psi.pro]
Reading /home/anton/prj/psi/iris/iris.pro
Reading /home/anton/prj/psi/src/src.pro
WARNING: /home/anton/prj/psi/src/src.pri:31: Unable to find file for inclusion /home/anton/prj/psi/src/libpsi/tools/tools.pri
WARNING: /home/anton/prj/psi/src/src.pri:35: Unable to find file for inclusion /home/anton/prj/psi/src/libpsi/dialogs/grepshortcutkeydialog.pri
WARNING: /home/anton/prj/psi/src/src.pri:90: Unable to find file for inclusion /home/anton/prj/psi/iris/iris.pri
 * returned: 3
 -> fail

Error: need Generate .prl files!

**Comment by antonte** [comment]
"git submodule update --init" helped
