### ISSUE TITLE
Emoji emoticons

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#217]
Provide a set of Emoji emoticons.

Personally, I am appalled by this trend; I am asking for Emoji so new users would not think that Psi is out dated, even though it is the best and most refined IM client, *though this may also be an opportunity to refresh the graphics of the current emoticon set*.

**Comment by Ri0n** [comment]
We already have emoji iconset. You can download it from psi+ project. It's compatible.

**Comment by GreenLunar** [comment]
Do you provide them by default in Psi?

**Comment by Ri0n** [comment]
should we?

**Comment by GreenLunar** [comment]
I don't know, maybe.  What type of emoticons do proprietary IM clients use, recently?

**Comment by Ri0n** [comment]
then a task for you. review other popular clients. review our emoji (every single smiley and icondef.xml for them) and report back with suggestions and updated iconpack.

**Comment by GreenLunar** [comment]
Noted!

I will see what I can do.
