### ISSUE TITLE
Psi starts, roster hides quickly (Qt5)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#221]
Detected last night, there is a bug with a value, 0 is impossible.

In roster option:
- Autohide roster after "x" seconds (0 - never)

Need to link to correction.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/psi-im/psi/commit/0e89e03594ee2343ada4d867f45b84007ac18310
- https://github.com/psi-im/psi/commit/7e0ec68a669278d1d247b30ccc36555773ec37fb
- https://github.com/psi-im/psi/commit/04456d26ae1eefa887997fb7f262330c0ea73cb9

**Comment by Ri0n** [comment]
better make pull request with option rename. it will solve the problem

**Comment by Ri0n** [comment]
fixed
