### ISSUE TITLE
If "start minimized", roster size/position problem and muc memberlist size problem too (Qt5)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#222]
For any start, the roster is centered and wrong size, and the muc memberlist has a bad size too.

You can change the roster size and position and the size of muc memberlist too.
Close completely, and start again...

**Comment by Ri0n** [comment]
Just checked with xfce and qt-5.7.  I don't see any problem with sizes.

**Comment by Neustradamus** [comment]
After a lot of tests, the problem exist with "start minimized" selected option.
If it is not select, no problem!

**Comment by Neustradamus** [comment]
In May 2018, if the "start minimized" option is selected, the problem is always here.

**Comment by tehnick** [comment]
https://github.com/psi-plus/main/issues/729

**Comment by Neustradamus** [comment]
- Problem with @Vitozz installer (x64+x86+webkit+normal)
- No problem with @Tehnick builds (x64+x86+webkit+normal)

**Comment by Neustradamus** [comment]
@tehnick: Solved?

**Comment by Neustradamus** [comment]
@tehnick, @Vitozz: I confirm that it is solved but what/where was the problem?
Before a specified Qt version?
If yes, what version?

**Comment by tehnick** [comment]
Bug is solved since Qt 5.12.0.
