### ISSUE TITLE
psi-plus segfault 

### ISSUE THREAD

**Issue by c327101** [psi-im/psi#228]
Hi!

When you open a chat window with the error falls

апр 13 23:41:39 host kernel: psi-plus[32746]: segfault at 0 ip           (null) sp 00007ffc87923cf8 error 14 in psi-plus[400000+834000]

Version Psi+ v0.16.545.533-webkit (20160413)
system gentoo

**Comment by Ri0n** [comment]
how can I reproduce this?
Please attach backtrace

I have the same version and gentoo. Works good for me.

**Comment by Vitozz** [comment]
Why error report about psi+ in psi-im/psi issues?

**Comment by c327101** [comment]
how to trace?

**Comment by Ri0n** [comment]
```
$ gdb psi-plus
> start
> continue
> bt full
```

**Comment by c327101** [comment]
GNU gdb (Gentoo 7.10.1 vanilla) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from psi-plus...(no debugging symbols found)...done.
(gdb) start
Function "main" not defined.
Make breakpoint pending on future shared library load? (y or [n]) 
Starting program: /usr/bin/psi-plus 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe08c8700 (LWP 17668)]
[New Thread 0x7fffe00c7700 (LWP 17669)]
[New Thread 0x7fffdf8c6700 (LWP 17670)]
[New Thread 0x7fffdf0c5700 (LWP 17671)]
[New Thread 0x7fffdd478700 (LWP 17672)]
[New Thread 0x7fffdcc77700 (LWP 17675)]
[00:16:11] W:PsiIconset::Private::iconsetPath("moods/silk.jisp"): not found
[00:16:11] W:libpng warning: iCCP: known incorrect sRGB profile
[00:16:11] W:PsiIconset::Private::iconsetPath("activities/psiplus-activities-16.jisp"): not found
[00:16:11] W:PsiIconset::Private::iconsetPath("clients/fingerprint.jisp"): not found
[00:16:11] W:PsiIconset::Private::iconsetPath("affiliations/medals-affiliations.jisp"): not found
[New Thread 0x7fffc6a3d700 (LWP 17679)]
[New Thread 0x7fffc623c700 (LWP 17680)]
[00:16:11] W:libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffc562b700 (LWP 17681)]
[New Thread 0x7fffc4e2a700 (LWP 17682)]
[00:16:12] W:QMainWindow::addToolBar: invalid 'area' argument
[00:16:12] W:QMainWindow::addToolBar: invalid 'area' argument
[00:16:12] W:QMainWindow::addToolBar: invalid 'area' argument
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  794 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  795 
[00:16:12] Unknown signature value:  7 
[00:16:12] Unknown signature value:  795 
[New Thread 0x7fff73538700 (LWP 17683)]
[00:16:13] unexpected version response

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) continue
Continuing.
[Thread 0x7fffdf8c6700 (LWP 17670) exited]
[Thread 0x7fff73538700 (LWP 17683) exited]
[Thread 0x7fffc4e2a700 (LWP 17682) exited]
[Thread 0x7fffc562b700 (LWP 17681) exited]
[Thread 0x7fffc623c700 (LWP 17680) exited]
[Thread 0x7fffc6a3d700 (LWP 17679) exited]
[Thread 0x7fffdcc77700 (LWP 17675) exited]
[Thread 0x7fffdf0c5700 (LWP 17671) exited]
[Thread 0x7fffe08c8700 (LWP 17668) exited]
[Thread 0x7ffff7f0c800 (LWP 17662) exited]
[Thread 0x7fffdd478700 (LWP 17672) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) bt full
No stack.
(gdb)

**Comment by c327101** [comment]
opening contact chat error occurs

**Comment by Ri0n** [comment]
First recompile with debug use flag. Second after receiving segmentation fault and getting back to gdb console type bt full . "continue" is necessary if the program stops in main function. But that's strange it didn't happen to you.

**Comment by c327101** [comment]
(gdb) start
Function "main" not defined.
Make breakpoint pending on future shared library load? (y or [n]) 
Starting program: /usr/bin/psi-plus 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe08c8700 (LWP 510)]
[New Thread 0x7fffe00c7700 (LWP 511)]
[New Thread 0x7fffdf8c6700 (LWP 512)]
[New Thread 0x7fffdf0c5700 (LWP 513)]
[New Thread 0x7fffdd478700 (LWP 522)]
[New Thread 0x7fffdcc77700 (LWP 531)]
[17:12:30] W:PsiIconset::Private::iconsetPath("moods/silk.jisp"): not found
[17:12:30] W:libpng warning: iCCP: known incorrect sRGB profile
[17:12:30] W:PsiIconset::Private::iconsetPath("activities/psiplus-activities-16.jisp"): not found
[17:12:30] W:PsiIconset::Private::iconsetPath("clients/fingerprint.jisp"): not found
[17:12:30] W:PsiIconset::Private::iconsetPath("affiliations/medals-affiliations.jisp"): not found
[New Thread 0x7fffc6a3d700 (LWP 547)]
[New Thread 0x7fffc623c700 (LWP 548)]
[17:12:30] W:libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffc562b700 (LWP 549)]
[New Thread 0x7fffc4e2a700 (LWP 550)]
[17:12:31] W:QMainWindow::addToolBar: invalid 'area' argument
[17:12:31] W:QMainWindow::addToolBar: invalid 'area' argument
[17:12:31] W:QMainWindow::addToolBar: invalid 'area' argument
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  794 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  795 
[17:12:31] Unknown signature value:  7 
[17:12:31] Unknown signature value:  795 
[New Thread 0x7fff73538700 (LWP 577)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) stop
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00000000008435b8 in ?? ()
No symbol table info available.
#2  0x00000000005f6671 in ?? ()
No symbol table info available.
#3  0x00000000005f9826 in ?? ()
No symbol table info available.
#4  0x000000000071df5b in ?? ()
No symbol table info available.
#5  0x0000000000732507 in ?? ()
No symbol table info available.
#6  0x00000000006ff3cd in ?? ()
No symbol table info available.
#7  0x000000000071a871 in ?? ()
No symbol table info available.
#8  0x000000000073295e in ?? ()
No symbol table info available.
#9  0x0000000000799417 in ?? ()
No symbol table info available.
#10 0x0000000000788034 in ?? ()
No symbol table info available.
#11 0x00007ffff46fef87 in QSortFilterProxyModel::setData(QModelIndex const&, QVariant const&, int) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#12 0x000000000078001a in ?? ()
No symbol table info available.
#13 0x000000000088ef8a in ?? ()
No symbol table info available.
#14 0x00007ffff38f191c in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#15 0x00007ffff4676c05 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#16 0x00007ffff46c0c23 in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#17 0x000000000078422b in ?? ()
No symbol table info available.
#18 0x00007ffff41ab1b7 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#19 0x00007ffff45669ae in QFrame::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#20 0x00007ffff4680a63 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#21 0x00007ffff46c2df0 in QTreeView::viewportEvent(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#22 0x000000000077fe50 in ?? ()
No symbol table info available.
#23 0x00007ffff38dcf96 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#24 0x00007ffff415749c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#25 0x00007ffff415e07f in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#26 0x00007ffff38dce2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#27 0x00007ffff415d6df in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#28 0x00007ffff41d3ac2 in ?? () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#29 0x00007ffff41d24bc in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#30 0x00007ffff41fa602 in ?? () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#31 0x00007ffff0892e9d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#32 0x00007ffff0893180 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#33 0x00007ffff089322c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#34 0x00007ffff390bf2e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#35 0x00007ffff41fa6c6 in ?? () from /usr/lib64/qt4/libQtGui.so.4
No symbol table info available.
#36 0x00007ffff38db981 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#37 0x00007ffff38dbce5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#38 0x00007ffff38e1269 in QCoreApplication::exec() () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#39 0x0000000000455b37 in ?? ()
No symbol table info available.
#40 0x00007ffff2657620 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#41 0x0000000000455ee9 in ?? ()
No symbol table info available.

**Comment by c327101** [comment]
#40 0x00007ffff2657620 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#41 0x0000000000455ee9 in ?? ()
No symbol table info available.
(gdb) quit
A debugging session is active.

        Inferior 1 [process 482] will be killed.

Quit anyway? (y or n) n
Not confirmed.
(gdb) continue
Continuing.
[Thread 0x7fff73538700 (LWP 577) exited]
[Thread 0x7fffc4e2a700 (LWP 550) exited]
[Thread 0x7fffc562b700 (LWP 549) exited]
[Thread 0x7fffc623c700 (LWP 548) exited]
[Thread 0x7fffc6a3d700 (LWP 547) exited]
[Thread 0x7fffdcc77700 (LWP 531) exited]
[Thread 0x7fffdd478700 (LWP 522) exited]
[Thread 0x7fffdf0c5700 (LWP 513) exited]
[Thread 0x7fffdf8c6700 (LWP 512) exited]
[Thread 0x7fffe00c7700 (LWP 511) exited]
[Thread 0x7ffff7f0c800 (LWP 482) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)

**Comment by Ri0n** [comment]
Ok. The trace is now more useful.
Can you please backup your ~/.config/psi+ and ~/.local/data/psi+ and then try to reproduce the bug w/o these directories.

Also check if problem is reproducible when you are offline.

If problem is not reproducible with newly created ~/.config/psi+ and ~/.local/data/psi+  and reproducible when you are offline I'd really like to receive your profile for investigation.

You can join our conference xmpp:psi-dev@conferecne.jabber.ru?join with any other client and we will discuss it there.

**Comment by c327101** [comment]
install (Psi + v0.16.476-webkit (20151217)) from backup and it works.
The new version does not work, rebuilt toolchain - does not work.
I will do as you have asked, and write the result

**Comment by Ri0n** [comment]
@c327101, are you still with us?
