### ISSUE TITLE
add support for full (unstripped) pgp message in <x xmlns='jabber:x:encrypted'> tag

### ISSUE THREAD

**Issue by sss123next** [psi-im/psi#235]
some client does not strip pgp tags from outgoing message and placing entire unstripped message inside <x xmlns='jabber:x:encrypted'>, psi+ just silently drops this kind of messages, please add support of unstripped pgp messages.

**Comment by tehnick** [comment]
> some client does not strip pgp tags from outgoing message and placing entire unstripped message inside

Personally I have not seen such clients. And such behavior is a violation of XEP:
https://xmpp.org/extensions/xep-0027.html

Please report bugs to developers of these xmpp clients.
