### ISSUE TITLE
XMPP server DNS changes : problem

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#247]
If a XMPP server changes of DNS, there is a problem, impossible to connect.
The app can crash.
We must close and reopen Psi.

https://github.com/psi-plus/main/issues/666

**Comment by Neustradamus** [comment]
Any news about this?

**Comment by Ri0n** [comment]
nope

**Comment by Neustradamus** [comment]
There was an investigation done or not?

**Comment by jkarneges** [comment]
I've observed this same problem in another project that uses jdns, so possibly this is a jdns bug. I've been unable to reproduce it in a test environment yet though.

**Comment by Ri0n** [comment]
currently we use only native Qt resolver in Psi since jdns has some problems with Qt5 and Qt4 is not supported anymore.
This bug is no more valid.

**Comment by Neustradamus** [comment]
@Ri0n: jdns supports Qt6:
- https://github.com/psi-im/jdns
