### ISSUE TITLE
Psi+ doesn't start anymore with some "qca ssl tls error"

### ISSUE THREAD

**Issue by ChrisDeChef** [psi-im/psi#267]
I updated to the recent version of psi+ three days ago and after restarting my system psi-plus won't start anymore. I always get the following error message:

If executed on a terminal:
> [20170308 23:00:06] W:PsiIconset::Private::iconsetPath("clients/default"): not found (psiiconset.cpp:74, PsiIconset::Private::iconsetPath)
> hmac support missing for voice calls, install qca-ossl
> [20170308 23:00:07] W:QMainWindow::addToolBar: invalid 'area' argument (unknown:0, unknown)
> [20170308 23:00:07] W:Accessing missing option plugins.options.clientswitcher.accsettlist (tools/optionstree/optionstree.cpp:59, OptionsTree::getOption)
> hmac support missing for voice calls, install qca-ossl
> hmac support missing for voice calls, install qca-ossl
> [20170308 23:00:07] registered dialog (alertmanager.cpp:53, AlertManager::dialogRegister)
> hmac support missing for voice calls, install qca-ossl

And afterwards it shows the following error dialog:

> Cannot connect: Encryption is enabled but no QCA2 SSL/TLS plugin is available.

or in German

> Verbindung fehlgeschlagen: Verschlüsselung ist aktiviert, aber es ist kein QCA2-SSL/TLS-Plugin verfügbar.

My specs:

- OS: **Linux Mint 18.1 XFCE**
- Installed Version of Psi+: **0.16.572.639-0ppa1~xenial1**
- Installed Version of libqca2-plugin-ossl: **2.1.1-2ubuntu1**

Any help is appreciated ;) Thanks in advance.

**Comment by tehnick** [comment]
sudo apt-get install libqca-qt5-2-plugins

**Comment by tehnick** [comment]
It is in recommends:
https://github.com/tehnick/psi-plus-debian/blob/launchpad/debian/control#L29

**Comment by ChrisDeChef** [comment]
Strange - I thought I tried this already and it didn't work.

But now it does. Big thanks for the fast reply!
