### ISSUE TITLE
Move profile folder

### ISSUE THREAD

**Issue by marcovtwout** [psi-im/psi#269]
Is there a way to use a profile folder outside of the default location?

**Comment by Ri0n** [comment]
try to play with PSI_DATADIR environment variable

**Comment by marcovtwout** [comment]
Just found that while looking through the source code, works as expected :) You can set the environment-var named "PSIDATADIR" to your preferred path.

https://github.com/psi-im/psi/blob/master/certs/README

**Comment by Ri0n** [comment]
Yep exactly. sorry for wrong name.
