### ISSUE TITLE
HTTPS for website

### ISSUE THREAD

**Issue by oodbur** [psi-im/psi#271]
the website psi-im.org should get a TLS certificate and then default to HTTPS.

**Comment by oodbur** [comment]
there's plenty of reasons to support HTTPS and almost no reasons against it anymore.
if not for the sake of giving visitors a little more privacy (e.g. when surfing from some dodgy wifi provider) then maybe to make the website more tamper proof (e.g. against ad injections) or to authenticate those downloads, share some hash values for the source code packages, ...
and if not for the practical benefits for the users maybe because Google and other browser vendors have already begun to force you to switch to HTTPS..? maybe because you would like to use HTTP/2 stuff that's only available together with TLS? Google awards HTTPS sites with a small pagerank bonus and browsers are already implementing steps of the plan to phase out unencrypted HTTP entirely.
and then it's also really easy to set up TLS with free certificates from letsencrypt and their automated setup stuff.
– what else should i say?..

**Comment by oodbur** [comment]
btw: the links to /files/snapshots/win/ and /files/snapshots/mac/ under #Nightly_Builds on /development/ as well as all those links to the /wiki/ are going nowhere.

**Comment by Ri0n** [comment]
We have temporary technical issues with https.
the /files/* links will be fixes as soon as we start making these snapshots.
We migrated to a new hosting just recently, so we need some human-hours to bring everything into decent state.

**Comment by tehnick** [comment]
Done. https://psi-im.org
