### ISSUE TITLE
No option to disable timestamps in chat window

### ISSUE THREAD

**Issue by puchuchoni** [psi-im/psi#272]
I've looked for it, but haven't found any option that will allow me to stop the timestamp from showing in the chat windows. Am I missing it? Can it be done?

Great chat client, by the way.

PS: Sorry if this is the wrong place to ask/request, I'm new to GitHub.

**Comment by Ri0n** [comment]
In case of webkit build build it's possible to use another theme.

**Comment by Ri0n** [comment]
legacy chatlog won't get much changes.
one of the next version will be based on qml where themes can be applied
