### ISSUE TITLE
Groupchats should be sorted alphabetically in account menu

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#277]
subj.
with a lot of bookmarks it's hard to find needed one.

**Comment by Neustradamus** [comment]
Commits done by @Ri0n, thanks:
- https://github.com/psi-im/psi/commit/7bb2093b762d420bdeb3a429799fb59d8b828280
- https://github.com/psi-im/psi/commit/b7e5e39948b4faf9332f77bbb50758c8bcc7bdda

This ticket is linked to:
- https://github.com/psi-im/psi/issues/316
