### ISSUE TITLE
version file does not correspond to what is expected in CMakeLists.txt

### ISSUE THREAD

**Issue by jirislaby** [psi-im/psi#283]
Recently, psi+ started failing to build:
```
../src/applicationinfo.cpp: In static member function 'static QString ApplicationInfo::version()':
../src/applicationinfo.cpp:50:22: error: 'PSI_VERSION' was not declared in this scope
 #define PROG_VERSION PSI_VERSION
                      ^        
../src/applicationinfo.cpp:76:9: note: in expansion of macro 'PROG_VERSION'
  return PROG_VERSION;
         ^~~~~~~~~~~~
../src/applicationinfo.cpp:50:22: note: suggested alternative: 'QT_VERSION'
 #define PROG_VERSION PSI_VERSION
                      ^        
../src/applicationinfo.cpp:76:9: note: in expansion of macro 'PROG_VERSION'
  return PROG_VERSION;
         ^~~~~~~~~~~~
```

Perhaps after 299ecb350066f7ba0db7d60a787fdb2dfbcfed6b -- @Vitozz 

The version file looks like (by https://github.com/psi-plus/psi-plus-snapshots/blob/master/generate-single-repo.sh#L209):
```
1.0.19.6a55a7a.345108b9 (2017-06-05)
```

But look what CMakeLists.txt expects while parsing this file:
https://github.com/psi-im/psi/blob/master/CMakeLists.txt#L105

So what I actually do to the version file before build is:
```
sed -i 's@^\([0-9]*\.[0-9]*\.[0-9]*\)\.\([a-fA-F0-9]*\)\.\([a-fA-F0-9]*\) \(.*\)$@\1.Psi+:\2.Psi:\3 \4@' version
```

To have:
```
1.0.19.Psi+:6a55a7a.Psi:345108b9 (2017-06-05)
```

**Comment by Vitozz** [comment]
According this commit https://github.com/psi-plus/main/commit/2ee4d5915b37ac94ae5ddae594ea1250713443a7
version of Psi+ night builds must be:
Example: 1.0.40 (2017-06-05, Psi:a7d2d7b8, Psi+:055e945, webkit)

**Comment by jirislaby** [comment]
> If you are using psi-plus-snapshots the version in version file from snapshots is obsolete

So what is the correct procedure to build psi+ from psi-plus-snapshots?

@tehnick Could you remove the file or generate a proper one?

**Comment by Vitozz** [comment]
You can set -DPSI_VERSION="version" flag by yourself. You can change version file. Or you can use ./configure script instead of CMake.

**Comment by jirislaby** [comment]
But neither is correct from the packager's perspective.

**Comment by Vitozz** [comment]
Added psi-plus-snapshots compatibility. Will be removed later.
Fixed
