### ISSUE TITLE
HIDPI displays support

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#285]
We had bugs like this already. But it still doesn't work good.
Icons in roster are not scaled. An option to install bigger icons does not sound good too. it's expected Psi out of the box just works and shows everything properly.

to test:
`xrandr --dpi 192 psi`

**Comment by pztrn** [comment]
On macOS with Retina displays it does 4x scaling, apparently.

**Comment by Ri0n** [comment]
as far as I know with the latest fixes everyone is satisfied
