### ISSUE TITLE
libgstprovider fails to load

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [psi-im/psi#286]
Hello guys !

Just to begin with: I've been using Psi/Psi+ for more than 7 years now as I find it to be one of the most comprehensive client (especially when you have administration rights).

Back to business... As v1 has been released, I've built it and tried to add Jingle (voice/video support) to Psi/Psi+ with [psimedia](https://github.com/psi-im/psimedia), but Psi or Psi+ does not add Jingle support.

I've been digging a bit the issue and it seems the plugin (`libgstprovider.so`, I'm under Linux) fails to load in `src/avcall/avall.cpp` at line 124 (at time of writing): `PsiMedia::PluginResult r = PsiMedia::loadPlugin(pluginFile, resourcePath);` returns an error. Looking in the psimedia subdir, `QPluginLoader::load()` in `PsiMedia::loadPlugin` (`src/psimedia/psimedia.cpp:171`) fails. This is as fare as I went, I don't know why Qt fails to load it.

I've tried with Psi and Psi+, with Qt4 and !t5. Here is a list of what I tried:
- Qt4 Psi with Qt4 libgstprovider.so;
- Qt4 Psi+ with Qt4 libgstprovider.so;
- Qt5 Psi with Qt5 libgstprovider.so;
- Qt5 Psi+ with Qt5 libgstprovider.so.

None of those worked.

However, the demo provided in the psimedia repository was always working, with both Qt4 and Qt5. And by working, I mean the transmission/reception test worked with both video and audio.

I've tried to diff the `psimedia` subdir of Psi and the one from the psimedia repo but the differences I've seen were non significant to me.

Some more details:
```bash
$ gcc --version
gcc (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 5.4.0
Copyright © 2015 Free Software Foundation, Inc.
```
binutils version 2.26.1

Qt version 5.6.2

Let me know if you need anything else.

**Comment by Ri0n** [comment]
Hi
Thanks for being with us!

Currently we ar working on 1.1 version which is going to be released very soon.
I promise to check psimedia with various configurations. But currently I can say it's loaded on my Gentoo system, Psi+ nightly, Qt-5.9. I see calls settings in options dialog.

As far as I remember it could happen when some gstreamer plugins are missing. But in this case I believe demo won't work too.

Did you install all the stuff from my overlay? (layman -a rion # and some unmask)

**Comment by StinGer-ShoGuN** [comment]
I did not use your overlay at all.

I'll double check the gst plugins, just in case. And I'll give a try to your overlay. I'll also try with Qt 5.9 (but if demo works with 5.6.2...) but I'd like to keep 5.6.2 as it's the official (I mean, for Gentoo) stable one for now.

**Comment by tehnick** [comment]
> Back to business... As v1 has been released, I've built it and tried to add Jingle (voice/video support) to Psi/Psi+ with psimedia, but Psi or Psi+ does not add Jingle support.

As far as I see you have tried outdated version of psimedia from repo [psi-im/psimedia](https://github.com/psi-im/psimedia). Try latest versions from repo [psi-plus/psimedia](https://github.com/psi-plus/psimedia).

**Comment by StinGer-ShoGuN** [comment]
Sorry for taking so long to reply, was busy at work.
So I tried tu update to Qt 5.7.1 (was willing to try 5.7 then 5.9): that was in fact a bad idea. Qt 5.7 is... well... And as I'm using Plasma, so it f***** up all my desktop. Still, I managed to compile and run Psi/Psi+ and psimedia with Qt 5.7 and it still didn't work.

I was actually too lazy to try with Qt 5.9. I would like to keep my current Plasma desktop working so I would need to set-it up in a PREFIX, etc... I'm lazy.

However, I've not tried @tehnick 's suggestion: I did not realise there were two psimedia repos. But still, when I compared sources in the psimedia directory from the Psi (or Psi+, don't remember) repo and the sources from the psimedia repo, the differences were minimal and limited to some Qt 5 support which was not relevant to this issue.

I'll try though, and I'll let you know.

**Comment by StinGer-ShoGuN** [comment]
Still failing... 😭 
```
[20170626 10:43:59] W:Attempted to load /usr/local/lib/psi-plus/plugins/libgstprovider.so, but it is not a valid plugin. (unknown:0, unknown)
[20170626 10:43:59] W:File is a plugin but not for Psi (unknown:0, unknown)
```

**Comment by tehnick** [comment]
@StinGer-ShoGuN Please reread my message above.

[psi-im/psimedia](https://github.com/psi-im/psimedia) repo is outdated, do not use it! Use [psi-plus/psimedia](https://github.com/psi-plus/psimedia) instead.

And if you will build both Psi+ and psimedia with Qt4 jingle calls will work fine. Other configurations are not supported for now.

**Comment by tehnick** [comment]
Games with Qt 5.x updates will not help you with this issue in any case.

**Comment by StinGer-ShoGuN** [comment]
@tehnick I was not clear but my last message reported a failure with the new repo.

I tried Qt 4 already (see my first message), still same issue.

And Qt is not very chatty about the error... I should have a look at how to increase its chattyness when loading modules.

**Comment by tehnick** [comment]
@StinGer-ShoGuN It your first message you have explicitly said that you have tried Qt4 build of Psi, but with outdated version of psimedia. BTW the most recent version of psimedia is 1.0.5. It was tested in Ubuntu Trusty and works fine with its libraries.

**Comment by Vitozz** [comment]
Show us output of ldd command ( use pastebin.com or similar)
>$ ldd /usr/bin/psi-plus
and
>$ ldd /usr/local/lib/psi-plus/plugins/libgstprovider.so

**Comment by StinGer-ShoGuN** [comment]
[psi-plus](https://pastebin.com/1fg4TGFG) linked libraries.
[libgstprovider](https://pastebin.com/r0JXscze) linked libraries.

Bonus: [my qt installation](https://pastebin.com/icH2ysvz)

**Comment by Vitozz** [comment]
https://github.com/rion-overlay/rion-overlay/blob/master/net-im/psimedia/psimedia-9999.ebuild

**Comment by StinGer-ShoGuN** [comment]
OK so I removed my psi-plus installation (from psi-plus-snapshot on tag 1.0.19) and installed psi and psimedia from rion's overlay. And... it worked. The only thing that comes to my mind that was different was the qtwebengine option: I enabled it when I manually compiled psi-plus. I disabled it with the ebuilds as it required Qt 5.7.
