### ISSUE TITLE
Provide user feedback when gpg hangs

### ISSUE THREAD

**Issue by Martchus** [psi-im/psi#290]
`gpg` might just hang. Eg. calling `gpg --list-secret-keys` as done internally by qca might hang when `gpg-agent` has been started incorrectly. In this case Psi should not hang as well without providing any user feedback because it is not obvious that Psi hangs because it is waiting for gpg.

### TODOs
* Get rid of `waitForBusyFinished()` and listen for `&QCA::KeyStoreManager::busyFinished()` instead. If that signal is not emitted after a certain amount of time, provide user feedback.
* Maybe even be able to start without KeyStoreManager being ready. Since it might turn busy again, this must be handled anyways.
* Maybe provide a way to increase log level of qca.

I would implement it myself when I have the time (the issue should not be too important). There are already comments in the code (`// FIXME get rid of this`) but I suppose no one is currently working on it?

**Comment by Ri0n** [comment]
It's merged and will be available in 2.0 version.
