### ISSUE TITLE
Can't configure PSI, QCA2 not found

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [psi-im/psi#291]
[Ubuntu 16.04, QT5]
I downloaded the latest QCA sources (2.1.3) from https://userbase.kde.org/QCA, where it's now kept.
I build it using:

    cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/qca2
    make
    make install

Back in PSI, I'm using:

    ./configure --prefix=/usr/local/psi --with-qca-inc=/usr/local/qca2/include --with-qca-lib=/usr/local/qca2/lib 

But the configure returns:

    Configuring Psi ...
    Verifying Qt build environment ... ok
    Checking for Qt >= 4.7.0 ... 4.8.7
    Checking for LibIDN ... yes
    Checking for QCA >= 2.0 ... no
    
    Error: need QCA >= 2.0!

What am I doing wrong?

**Comment by Napoleon-BlownApart** [comment]
The test is failing in line 905:

    if(!conf->doCompileAndLink(str, QStringList(), QString(), proextra + "CONFIG += release\\n", &ret) || ret != 0)

I installed QT5.9.1 using qt-unified-linux-x64-3.0.0-online.run

**Comment by Vitozz** [comment]
You forgot to set -qtselect=5 flag while configue

**Comment by Napoleon-BlownApart** [comment]
@Vitozz :  Unfortunately `--qtselect` didn't fix the problem.  All it did was make the config recognise my QT5 install:

    Checking for Qt >= 4.7.0 ... 5.5.1

**Comment by Vitozz** [comment]
You can use cmake to build psi. There is Readme file in root dir.

**Comment by Vitozz** [comment]
Or you can try to add pathes to qca library to PATH variable

**Comment by Ri0n** [comment]
well if cmake way works then the binaries are fine and compatible.
and the problem is in correct pathes

**Comment by lyn1337** [comment]
I think so, just went the cmake way and it was working as intended for me.
