### ISSUE TITLE
Crash when searching MUC history

### ISSUE THREAD

**Issue by cweiske** [psi-im/psi#297]
While searching history/log of a MUC, psi-plus crashes for me. Seems to be when I typed something, it wasn't found and I press backspace to delete the search text.

happens with Psi+ v1.0.136 (2017-07-17, Psi:e6eb5ad4, Psi+:45955e6)

> Thread 1 "psi-plus" received signal SIGSEGV, Segmentation fault.
0x00007ffff672c8c8 in QActionPrivate::setShortcutEnabled(bool, QShortcutMap&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5

Full backtrace:
[bt.txt](https://github.com/psi-im/psi/files/1155296/bt.txt)

**Comment by Vitozz** [comment]
Please check crash in new version os Psi+ (2017.07.24)

**Comment by cweiske** [comment]
Works fine with Psi+ v1.0.140 (2017-07-18, Psi:f455fc84, Psi+:cdfa2a3) - no crashes anymore.
