### ISSUE TITLE
Psi doesn't recognize message stanza as a message

### ISSUE THREAD

**Issue by caduellery** [psi-im/psi#300]
We have an IM web client that sends the following message to Psi but it doesn't show:

```xml
<message from="user-a@im.host/webclient" type="chat" to="user-b@im.host/Psi">
<active xmlns="http://jabber.org/protocol/chatstates"/>
<html xmlns="http://jabber.org/protocol/xhtml-im">
<body xmlns="http://www.w3.org/1999/xhtml">do you see this?</body>
</html>
</message>
```
Other clients, like Pidgin, shows the message. Anyone know why? Is this a malformed stanza?

**Comment by Ri0n** [comment]
probably because of missing body

**Comment by Ri0n** [comment]
xhtml-im spec  says html element is a formatted representation of message->body element which is absent  in your example. So it's fine such a non-standard message is ignored.
