### ISSUE TITLE
Subject is not shown sometimes (based on language?)

### ISSUE THREAD

**Issue by Voker57** [psi-im/psi#307]
There are two conferences I join, one has empty subject in Psi (despite actually having one), the other works fine. Respective XML (scrubbed):

```
<message from="xxx@conference.xxx/xxx" type="groupchat" to="xxx@conference.xxx/xxx">
<subject>subj</subject>
</message>

<message from="xxx@conference.xxx/xxx" type="groupchat"  to="xxx@conference.xxx/xxx">
<subject xml:lang="en">тема</subject>
</message>
```

Can give addresses of said conferences for testing.

**Comment by Ri0n** [comment]
language-based subject should work. code was changed a few months ago. please check.

**Comment by Voker57** [comment]
Yes, it works now, thanks
