### ISSUE TITLE
Connection to xmpp server using manually set IP address is broken

### ISSUE THREAD

**Issue by tehnick** [psi-im/psi#311]
Bug was initially found in Debian Sid: https://bugs.debian.org/874481
Also bug was successfully reproduced in Debian Buster.
gcc version 7.2.0 + Qt version 5.9.1 are currently used there.

Next, bug was reproduced in Ubuntu Zesty (17.04).
gcc version 6.3.0 + Qt version 5.7.1 are used there.

In GNU/Linux systems with older gcc and Qt versions all works fine.

After quick research using `git bisect` the problematic commit was found:
https://github.com/psi-plus/psi-plus-snapshots/commit/dbe72e86f0f5d1c3e57905f9fe650787dd56f818

This leads us to the commit:
https://github.com/psi-im/iris/commit/6ac4867811428a658a24ba4536d024099ce954d7

**Comment by tehnick** [comment]
[12:10:40] <rion☫> хм может оно IP в libresolv спускает и того от этого плющит и таращит.. 
[12:14:37] <rion☫> надо попробовать простой хак сделать. загнать name в QHostAddress. если распарсилось, то сразу идти на выдачу результатов. а если нет, то отправлять в QDnsLookup

**Comment by tehnick** [comment]
As a workaround I now build all packages for Debian, for Ubuntu and for Windows using undocumented configuration option `-DUSE_QJDNS=ON`.

**Comment by tehnick** [comment]
New a workaround in libiris https://github.com/psi-im/iris/commit/6a590575c31ff6c9191bd26640089196f697bd0b fixes problem too.

**Comment by samweisgamdschie** [comment]
Psi also does not connect in our environment, where we have a servername that differs from the JIDs server Part. I tried it with the DNS alias, the A record and the IP address without success.

**Comment by tehnick** [comment]
@samweisgamdschie Fixed in Psi 1.3.

**Comment by samweisgamdschie** [comment]
should it be fixed under windows too? I tried version 1.3 with the same (not connecting) result. Is there a way to see some log output under windows?

**Comment by tehnick** [comment]
@samweisgamdschie 
Try portable [builds](https://sourceforge.net/projects/psi/files/Psi/1.3/). They are [built](https://groups.google.com/d/msg/psi-users/0V8mx8Jmchs/mzgC22uOAQAJ) using MinGW.

If portable builds for Win7 will not work for you, try a build for WinXP. They are using different DNS resolvers.

**Comment by samweisgamdschie** [comment]
FYI

portable-win7 version does not even start: _'This application failed to start because it could not find or load the Qt plattform plugin "windows" in "".'_

portable-winxp version starts and connection works fine. This app bundle looks like a non-installing-software. The question is: is it possible to use it with all (about 20) Users on a single machine?

**Comment by tehnick** [comment]
> portable-win7 version does not even start:

I have just rechecked VirtualBox: all work fine in clean Win8.1 environment.

> This app bundle looks like a non-installing-software. This app bundle looks like a non-installing-software. The question is: is it possible to use it with all (about 20) Users on a single machine?

Why not? You may move unpacked directory to "Program Files" and create shortcuts (*.lnk files). Just do not forget to read a note about user profiles in README.txt.

> Do I need to use the global Psi profile for our case?

Yes, if you want to have only one copy of Psi executable file and related libraries in your system.

**Comment by samweisgamdschie** [comment]
it's a windows server 2012 (R2 I think) with Citrix we use.

I only asked because I dont know where this app-bundle stores the users information and thought of a usecase with this app on a USB stick.

OK, I'll try it this way, thx!
