### ISSUE TITLE
set text format bug in muc

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#317]
I found a bug, if we set text format in muc it does not work (chat window message it works).

- Muc test:
![muc-test-bold-etc-1](https://user-images.githubusercontent.com/104737/30815607-f8d16b94-a213-11e7-8441-1d007658991e.png)
- Result:
![muc-test-bold-etc-2](https://user-images.githubusercontent.com/104737/30815627-04d910b8-a214-11e7-94f8-0db041248020.png)
- Chat window message test, it works:
![private-message-test-bold-etc](https://user-images.githubusercontent.com/104737/30815653-1190666c-a214-11e7-9715-6909791d69ca.png)

**Comment by Ri0n** [comment]
Most likely you have html rendering disabled

**Comment by Ri0n** [comment]
works good for me
Psi+ v1.2.71 (2017-09-11, Psi:2cb4866e, Psi+:43fb3ea, webkit)

**Comment by Neustradamus** [comment]
Can you enable the option by default?

Like options -> html -> chat -> render : true
options -> html -> muc -> render : false to true

**Comment by Ri0n** [comment]
in general people are happy with current defaults. I while I'd prefer html too I don't know if others accept it.
