### ISSUE TITLE
Strange issue potentially with locales on Centos 7, docker.

### ISSUE THREAD

**Issue by jarekg83** [psi-im/psi#320]
Hi,

I'm trying to build a docker container with PSI within it however I'm experiencing very strange error with the language when I ran it from inside the container. 

This is my Dockerfile:
https://github.com/jarekg83/psi/blob/centos/Dockerfile

When I run PSI from this container all the fonts seem to be... either form the language which my OS doesn't support or something is completely wrong. 

As you can see on the picture below this is the first screen:

![image](https://user-images.githubusercontent.com/14975295/31269235-7803db84-aa77-11e7-84e3-3cc10a78fb58.png)

I found some issues on the internet related to locales being broken in CentOS 7 due to yum.conf setting override_install_langs=en_US.utf8 which I commented out and reinstalled glibc-common but it didn't help and I still get the same issue. Once PSI compiled on the host (also CentOS 7) I have no issues at all.

Any help really appreciated. 

Thank you.

**Comment by jarekg83** [comment]
Definitely issue with CentOS 7 docker base image. On Ubuntu everything works smoothly... (some of the XCB errors occur sometimes but... not a big deal)

**Comment by Ri0n** [comment]
I believe Qt reads a lot of info from system to configure fonts. Docker image may not have all the necessary stuff.
I'd read something about how to start arbitrary Qt application in docker. not just Psi.
