### ISSUE TITLE
Editing of last message is broken in basic Psi version

### ISSUE THREAD

**Issue by tehnick** [psi-im/psi#321]
In webkit and webengine builds this feature works as expected. But in basic Psi build you may edit last message only one time. All next attempts will be ignored.

**Comment by Vitozz** [comment]
А это точно баг и так не задумано автором (rkfg)?

**Comment by Ri0n** [comment]
Кажется оно раньше работало и наверное сломалось когда я делал более унифицированный интерфейс для вебкита и без

**Comment by Ri0n** [comment]
as far as I know it was fixed with some my changes. and later tested
