### ISSUE TITLE
Can psi auto-reconnect back to Available state?

### ISSUE THREAD

**Issue by bialix** [psi-im/psi#323]
I've tried to find such an option in settings but found nothing. Psi is disconnecting from some server (at my work) from time to time, esp. when laptop is switching to sleep mode, and then I have to manually select 'Available' in roster window to connect back. 

Can Psi do it for me automatically?

**Comment by Ri0n** [comment]
yes it can. It's in account settings dialog. You can find it in account context menu or in accounts manager

**Comment by bialix** [comment]
OK, sorry, спрятано очень хорошо.
