### ISSUE TITLE
Remember state of collapsed/expanded groups in roster

### ISSUE THREAD

**Issue by bialix** [psi-im/psi#324]
Every time I reconnect to my server the roster window is opened with all groups expanded. With as many as 50+ people in dozen groups - it's quite tiresome to collapse all groups back to desired state.

Why Psi don't try to remember my previous state?

**Comment by Ri0n** [comment]
There was an option for this and it's enabled by default as far as I remember.
What version do you use?

**Comment by bialix** [comment]
Psi v.1.3, downloaded and installed just couple of days ago.

**Comment by Ri0n** [comment]
is it on Windows? official release by link from psi-im.org?
I can't reproduce the issue.

**Comment by Ri0n** [comment]
Can anyone reproduce this?
I can't neither with Psi (default settings) nor with Psi+.

**Comment by Neustradamus** [comment]
I have sometime account and groups (normally closed) expanded at start...
I do not know why.

It is possible to add feature, close/expand all accounts and close/expand all groups?

**Comment by Ri0n** [comment]
I closed this until someone will tell me how to reproduce

**Comment by Zlatov** [comment]
It's easy to repeat the mistake. Ubuntu is clean. Install psi+, enter account parameters, 1000+ people in the company, all groups are open. 5 minutes you sit, poke, hide the groups. We restart the application. We hold back the scream. The app doesn't even have a way to "collapse all groups". In additional options:
options: contactlist: group-state: collapsed: true

**Comment by tehnick** [comment]
Which version of Psi+ are you using?
