### ISSUE TITLE
Make Filetransfer alway working

### ISSUE THREAD

**Issue by Tesla2k** [psi-im/psi#328]
Hello,
event today file transfer behind a NAT is not working out of the box. I think this should be changed. I have a prosody server with XEP-0065 enabled. But now I would need to enter the proxy on every single client. I would suggest the following default behaivoir for PSI.

1. On Login check with service discovery if there is a XEP-0065 proxy on the server. If yes then use it
2. When filetransfer fails automatically use inband transfer and continue the transfer transparently. Maybe with a small warning note in the transfer windows that inband transfer is used an that this could be slow.

I think this would make it much more userfriendly.

**Comment by Ri0n** [comment]
I agreed about disco, but don't remember which xep describes such fallback mechanism?
Is it in jingle? Jingle FT is still not supported :-(

**Comment by Tesla2k** [comment]
I dont't know if this is somewhere in a xep. Its just how I think it should work. The reason why today everybody uses WhatsApp is because there everything just works. I think it would be good to get to this point with xmpp also.

**Comment by Ri0n** [comment]
agreed. Do you want to join our team and help us with that? :-)

**Comment by Ri0n** [comment]
everything is implemented with help of Jingle.
use nightly builds (https://sourceforge.net/projects/psiplus/files/Windows/Personal-Builds/)  to get it early.
