### ISSUE TITLE
Wrong tags with git describe

### ISSUE THREAD

**Issue by sirlucjan** [psi-im/psi#329]
Could someone refresh tags? The newest version is 1.3. When I've used git describe --tags:

git describe --tags
0.15-1010-g8693e2e0

Or tell me if I get something wrong.

**Comment by Ri0n** [comment]
current latest tags are set on release-1.x branch. next 2.0 release will start from master and then branched to release-2.x.
I don't know what  you are going to do. But probably you shouldn't.

**Comment by sirlucjan** [comment]
I'm trying to get the newest version:

https://github.com/archlinux-lucjan/archlinux-packages/blob/master/psi-git/PKGBUILD 

git describe --tags doesn't work properly - I'm getting a very old version: 0.15-1010-g8693e2e0

Of course I've another solution:

pkgver() {
    cd $srcdir/psi
    _ver="$(cat version | grep -o "[[:digit:]]*" | paste -sd'.')"
    echo "${_ver}.r$(git rev-list --count HEAD).g$(git rev-parse --short HEAD)"
}

But it would be a temporary solution.

Regards.

**Comment by Ri0n** [comment]
check admin/git_revnumber.sh script. that's probably exactly what you need.
