### ISSUE TITLE
<subject xml:lang="en"></subject> in muc psi don't set subject

### ISSUE THREAD

**Issue by wkg** [psi-im/psi#331]
new ejabberd send `<subject xml:lang="en"></subject>`, psi don't understand it...
old ejabberd send `<subject></subject>` - psi understand it.

**Comment by Ri0n** [comment]
which version?

**Comment by wkg** [comment]
1.3

**Comment by Voker57** [comment]
Can reproduce with Psi from git

**Comment by wkg** [comment]
Я так понимаю тут понимают русский... А с ингишем у меня не очень.
В ejabberd это пофиксили, но поидее psi это всё равно должен понимать по стандартам...
Я попробовал собрать psi без русского языка(подумал может он наоборот это очень хорошо отрабатывает и не показывает на русском если xml:lang="en"), но нет.
И да, тоже проверил в git версии - всё так же

**Comment by Ri0n** [comment]
переделал немного отображение топика в зависимости от текущей локали. если по текущей локали ничего не найдено в топиках, оно будет пробовать без xml:lang.
так же стало возможным установить топик сразу для нескольких языков.
