### ISSUE TITLE
Some items of main menu (e.g. "Add a Contact") are auto clicked in global menu

### ISSUE THREAD

**Issue by andreymal** [psi-im/psi#335]
Steps to reproduce:

- Install and configure any global menu applet on MATE desktop environment (e.g. topmenu or vala)

- Install and run any version of Psi (Psi or Psi+, Qt4 or Qt5 — this problem can be reproduced with any version)

- Add __two or more__ jabber accounts

- Move mouse cursor to global menu item "General" → "Add a Contact"

- This will be auto clicked!

Video with topmenu applet: https://www.youtube.com/watch?v=CTp5PwVdqKU

Video with vala applet: https://www.youtube.com/watch?v=d73AObkPcKM

Developers of topmenu and vala say that the problem is probably not in the global menu. Maybe this is Psi bug, so I try to report here. But unfortunately I'm not an C++ expert and I can't debug it.

**Comment by Vitozz** [comment]
Посмотрел видео. Какой-то непонятный виджет и проблема скорее всего именно в нём (в них), возможно какая-то несовместимость gtk<->qt или кривость реализации. к тому же в терминале постоянно лезет ошибка (на видео) связанная с меню и да сегфолт в процессе демонстрации тоже наводит на мысль. В мате вообще много кривости в работе с qt, например стоит свернуть в трей и обратно развернуть ростер и он сместится влево. В других ДЕ такого не наблюдается.

**Comment by andreymal** [comment]
А, да, проблема оказалась в нём и она уже исправлена, я забыл эту задачу закрыть.)

**Comment by liuch** [comment]
> В других ДЕ такого не наблюдается.

Такая ерунда может быть из-за особой qt темы в мате. Я нарывался с псинкой и с какой-то темой, когда сидел под кедами. Подробностей уже не помню. Тема использовала какой-то дополнительный виджет для своих целей. Но дело было не в смещении.
