### ISSUE TITLE
link-color

### ISSUE THREAD

**Issue by scuq** [psi-im/psi#337]
<chat>
      <link-color type="QColor">#00ff21</link-color>

doesn't apply in chat window, tried to set the link color for my custom dark skin by

<options.ui.look.colors.chat.link-color type="QColor">#00ff21</options.ui.look.colors.chat.link-color>

color is set in options.xml but doesn't get applied within the qlineedit? in the chat window, may I ask you to look into this problem?

![image](https://user-images.githubusercontent.com/10185017/34366492-a9dd9d60-ea9c-11e7-9119-63f9b43a881c.png)

**Comment by Ri0n** [comment]
It's still a part of Psi+.
It won't be integrated to Psi until it's properly implemented for both QTextEdit and webkit versions. And they should not conflict with each other.
I'd start with QPalette but I'm not sure if it works after lots of complains I saw on the Internet.

**Comment by Ri0n** [comment]
implemented
