### ISSUE TITLE
Error: Could NOT find Qca (missing: Qca_INCLUDE_DIR) 

### ISSUE THREAD

**Issue by sirlucjan** [psi-im/psi#338]
Psi-plus - version 1.2.152.0.gdafff58e

I've downloaded the latest commit.

```
  cd psi-plus-snapshots
  mkdir -p build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
  make
```

I got an error:

```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Qca (missing: Qca_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindQca.cmake:71 (find_package_handle_standard_args)
  iris/CMakeLists.txt:42 (find_package)


-- Configuring incomplete, errors occurred!
```

I've installed the newest qca:

```
pacman -Qs qca    
local/qca-qt5 2.1.3-6
    Qt Cryptographic Architecture
```

**Comment by sirlucjan** [comment]
Solved. I've improved cmakelist:

https://github.com/sirlucjan/psi-plus-snapshots/commit/b3e7324996033340ea53d93271573cbd63f0879e

Ít works perfect for me!

**Comment by sirlucjan** [comment]
If you want I can send a pull request with changes.

**Comment by Ri0n** [comment]
Do I understand it right it's qca who installs invalid cmake modules on Arch Linux?

**Comment by sirlucjan** [comment]
Probably not.

#291 - the same problem, qca is installed but it's not recognized

I've added path to qca and now qca is detected.

**Comment by Martchus** [comment]
@Ri0n I've just checked the CMake files for qca under Arch Linux and those look fine.

```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Qca (missing: Qca_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindQca.cmake:71 (find_package_handle_standard_args)
  iris/CMakeLists.txt:42 (find_package)


-- Configuring incomplete, errors occurred!
```

I suppose the only problem is that the CMake script looks for `Qca`, but the package is actually called `Qca-qt5` for the Qt 5 version which is required here. The Arch Linux package [does not seem to change that package name](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qca), so I would assume it is default.

---

@sirlucjan I've just read your patch. Generally, it is not a good idea to use `include_directores`. Just to link properly against the `qca-qt5` target should be sufficient. So if include directories make problems, I suspect that this isn't done right.  
BTW: If you need the include directory explicitly in a variable, just use `get_target_property(VAR target property)` on target `qca-qt5` to read the property `INTERFACE_INCLUDE_DIRECTORIES`, eg. `get_target_property(Qca_INCLUDE_DIR qca-qt5 INTERFACE_INCLUDE_DIRECTORIES)`.

**Comment by sirlucjan** [comment]
Fox example, konversation needs qca. 

find_package(Qca-qt5 2.1.0)
set_package_properties(Qca-qt5 PROPERTIES DESCRIPTION "Support for encryption"
                       URL "http://download.kde.org/stable/qca-qt5/"
                       TYPE OPTIONAL)

https://cgit.kde.org/konversation.git/tree/CMakeLists.txt

find_package(Qca-qt5 2.1.0)
set_package_properties(Qca PROPERTIES DESCRIPTION "Support for encryption"
                       URL "http://delta.affinix.com/qca"
                       TYPE REQUIRED)

https://cgit.kde.org/kget.git/tree/CMakeLists.txt

Many of distros (Debian, Ubuntu, Fedora, Arch) use simply qca-qt5.

I think that change qca to qca-qt5 solve the problem.

**Comment by Vitozz** [comment]
Psi uses built-in module to find qca. Look at cmake/modules

**Comment by sirlucjan** [comment]
It's my second attempt.

https://github.com/archlinux-lucjan/psi-plus-snapshots/commit/f3372d84595d10b757de4568399707bc721f6850

```
-- Psi+ features - FOUND
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QtWebEngine - enabled
-- Webkit - enabled
-- Found Psi version file: /home/lucjan/Pracownia/Teraz/pilne/psi-plus-git/src/psi-plus-snapshots/version
-- Psi version found: 1.2.153
-- Psi revision found: 0b4ed675
-- Psi+ revision found: 3667274
-- CXX flags: -march=native -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11 -Wall -Wextra
-- C flags: -march=native -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra
-- Found IDN: /usr/lib/libidn.so  
-- Found ZLIB: /usr/lib/libz.so  
-- Found XCB: /usr/lib/libxcb.so  
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Found Hunspell: /usr/lib/libhunspell.so  
-- Psi+ version set: 1.2.153 (2018-01-07, Psi:0b4ed675, Psi+:3667274, webengine)
-- Psi+ libraries directory: /usr/lib/psi-plus
-- Psi+ data directory: /usr/share/psi-plus
-- Configuring done
-- Generating done
```

**Comment by Martchus** [comment]
@Vitozz Apparently CMake is not able to find that one. At least not using `find_package(Qca REQUIRED)`.

@sirlucjan Yep, that's what I've meant. You don't need `include_directories`. You have just found the most elegant solution: just use the package provided by QCA itself. So the patch looks good from my point of view (I'm not a psi developer).

**Comment by sirlucjan** [comment]
Separate patches:

iris - https://github.com/sirlucjan/iris/commit/570ea2e604586efc04e8b05cbe286f472ec41013

psi - https://github.com/sirlucjan/psi/commit/48b89f3bc0fe01145d7ce2fbf02d7eda4fb7fd0f

Works fine.

**Comment by Vitozz** [comment]
did you try to compile?

**Comment by sirlucjan** [comment]
Yup. Works.

**Comment by sirlucjan** [comment]
```
ls
conf.diff   pkg                                                   psi-plus-git-1.2.153.1.gf3372d84-1-x86_64.pkg.tar.xz.sig
join.patch  PKGBUILD                                              psi-plus-snapshots
main        psi-plus-git-1.2.153.1.gf3372d84-1-x86_64.pkg.tar.xz  src
```

**Comment by Vitozz** [comment]
As I see the problem is in a path to Qca includes. 
in your system the path is: /usr/include/qt/Qca-qt5/QtCrypto
in other systems (debian, ubuntu, gentoo): /usr/include/qt5/Qca-qt5/QtCrypto

**Comment by sirlucjan** [comment]
@Vitozz 

It doesn't matter.

Psi need to qca-qt5 - I've switched Qca to Qca-qt5 and compile without errors. 

If you want I can run Debian or Ubuntu on VB...

**Comment by Vitozz** [comment]
code in cmake lists
set(Qca_SUFFIX -qt5)

code from modules/FindQca
if("${Qca_SUFFIX}" STREQUAL "-qt5")
    set(EXTRA_PATH_SUFFIXES
        qt5/Qca-qt5/QtCrypto
        Qca-qt5/QtCrypto
        qt5/QtCrypto
    )
endif()

find_path(
    Qca_INCLUDE_DIR ${LIBINCS}
    HINTS
    ${QCA_DIR}/include
    PATH_SUFFIXES
    QtCrypto
    ${EXTRA_PATH_SUFFIXES}
)
...

**Comment by sirlucjan** [comment]
Maybe you could add "if" with Arch Linux variable? Maybe it will solve the problem?

**Comment by Vitozz** [comment]
try now please

**Comment by Vitozz** [comment]
oh sorry, i've forgot, new snapshots will be available in an hour

**Comment by sirlucjan** [comment]
pkgver=1.3_dev_20180107

```
-- Psi+ features - NOT FOUND
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QtWebEngine - enabled
-- Webkit - enabled
-- Found Psi version file: /home/lucjan/Pracownia/Teraz/pilne/psi-git/src/psi/version
-- Psi version found: 1.3
-- CXX flags: -march=native -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11 -Wall -Wextra
-- C flags: -march=native -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra
-- Production version - ENABLED
-- Found Qca: /lib/libqca-qt5.so  
-- Found IDN: /usr/lib/libidn.so  
-- Found ZLIB: /usr/lib/libz.so  
-- Found XCB: /usr/lib/libxcb.so  
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Found Hunspell: /usr/lib/libhunspell.so  
-- Psi version set: 1.3
-- Psi libraries directory: /usr/lib/psi
-- Psi data directory: /usr/share/psi
-- Configuring done
-- Generating done
```
Seems to be working just fine.

**Comment by Martchus** [comment]
@sirlucjan Can you share your CMake-based PKGBUILD?

**Comment by sirlucjan** [comment]
@Martchus 

https://aur.archlinux.org/packages/psi-plus-git

I've added my patch.

**Comment by Vitozz** [comment]
If you want you can join psi-dev@conference.jabber.ru to chat with psi/psi+ developers and maintainers.

**Comment by sirlucjan** [comment]
Solved. Thanks!
