### ISSUE TITLE
Psi/+ TLS connection crashs after several OMEMO messages sent

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#361]
Tested on Windows, after several OMEMO messages, the Psi or Psi+ TLS connection crashs.
Sender server: jabber.org

**Comment by Bigoukun** [comment]
Other user, other servers, same problem. On Windows, after several OMEMO messages, the Psi or Psi+ TLS connection crashs.
Sender servers: jappix.com, mondiaspora.net

**Comment by Ri0n** [comment]
this issue is related to a plugin. it had to be created in plugins repo.

**Comment by stigger** [comment]
Should be fixed starting from 1.3.384.
