### ISSUE TITLE
Plugin options: problem if we open two "plugin settings dialog"

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#364]
Problem if we open two "plugin settings dialog":
- The first is ok
- The second is ok but now the first is in grey (not at all usable)

Solution: We must to open only one "plugin settings dialog".

**Comment by Ri0n** [comment]
not reproducible on linux

**Comment by Vitozz** [comment]
This can be fixed by setting settings dialog as modal (change the bringToFront method to the open method)

**Comment by Vitozz** [comment]
Fixed in https://github.com/psi-im/psi/commit/2b6b03a639034fdce7874ef23ea2b72d68d48bc1
