### ISSUE TITLE
Add the XMPP logo for "XMPP" service in "Add Contact"

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#370]
Add the XMPP logo for "XMPP" service in "Add Contact"

**Comment by Ri0n** [comment]
not needed

**Comment by Ri0n** [comment]
hm for transports it has icons. but for plain xmpp has not. may be you are right

**Comment by Neustradamus** [comment]
@rion: Can you update the logo (without text)?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png
