### ISSUE TITLE
Can't see my OTR messages.

### ISSUE THREAD

**Issue by DenOwens** [psi-im/psi#379]
My OTR-encrypted messages look in encrypted form in the chat window, but my contact see it in normal form.

Example here: https://pastebin.com/pQ9NzZnb

Please solve it, thank you.

Psi+ v1.3.375 (2018-06-12, Psi:c2bc9d97, Psi+:a7d8ec8) 
OTR plugin: 1.0.4
System: Linux john-virtual-machine 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tehnick** [comment]
Fixed in https://github.com/psi-im/plugins/commit/65728c257b5d4c8ff5034e60d6c8dddab5221a23

Use latest builds of program.
