### ISSUE TITLE
FR: single chat window for multiple resources

### ISSUE THREAD

**Issue by woj-tek** [psi-im/psi#393]
Currently resource name is less significant, especially for end user and with more and more clients/servers adopting randomised resources it's getting a bit annoying as each messages from new resource opens in separate window. It would be nice to have option to have chat windows per BareJID instead per FullJID.

Edit:
there is `options.ui.chat.default-jid-mode` but setting it to `barejid` doesn't seem to work.

**Comment by tehnick** [comment]
![screenshot_20181107_085525](https://user-images.githubusercontent.com/441190/48113529-4febd100-e26c-11e8-8961-d664af6eff85.png)
