### ISSUE TITLE
The specified resource in the XMPP account is not the same used (random bug)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#397]
The specified resource in the XMPP account is not the same used, it is a random bug.
Example : "a8g51e4m6e391q37" instead of "client"

**Comment by Ri0n** [comment]
please show xml log from the moment of login till use see wrong resource. There is nothing in the code capable to generate such a random string. So I suppose it's not a client problem. It's rather some new standards which say we shouldn't use resources at all.

**Comment by Ri0n** [comment]
@Neustradamus, I'll close this till you have xml log, or somebody else has.
