### ISSUE TITLE
Remove bad and old dead email addresses from Authors in About box

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#399]
All psi-im.org email addresses are dead since a long time, please remove it and replace for Justin and Kevin like specified in README:
- https://github.com/psi-im/psi/blob/master/README.md

**Comment by Ri0n** [comment]
Both Kevin and Justin have commit access to this repo. They can change it to whatever they want.

**Comment by Ri0n** [comment]
Kev just did his changes to about dialog, but it seems he is fine with current readme. 
Justin did the changes to readme before.

**Comment by Neustradamus** [comment]
Thanks @jkarneges :)

And for @mblsha and @maciejniedzielski?
New email address or removal?

**Comment by mblsha** [comment]
Remove my email, please.
