### ISSUE TITLE
[Forum] Psi and Psi+ duplication

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#403]
The https://forum.psi-im.org/ is dead since a very long time.

And there is a psi-users Google group: https://groups.google.com/forum/?_escaped_fragment_=forum/psi-users#!forum/psi-users

It will be nice to have only one, close the google group?
And redirect http://forum.psi-im.org/ and https://forum.psi-im.org/ to https://forum.psi-plus.com/?

In the same time, an update of the code of course.

- https://github.com/psi-im/psi/blob/master/src/tipdlg.cpp
- https://github.com/psi-im/psi/blob/master/src/mainwin.cpp
- https://github.com/psi-plus/main/blob/master/patches/9970-psiplus-join-to-support-muc.diff

**Comment by tehnick** [comment]
Do not mix the things please. Psi+ is Psi+, Psi IM is Psi IM. They have different user base, different forums and other contacting channels (groups on vk.com, facebook.com, etc.).

As for link to Psi forum it is fixed in 6aea3b90bea5b9b86f9c128878a7b5430e637b67. Thanks.
