### ISSUE TITLE
[Website] Bad links and bad parts

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#405]
On https://psi-im.org/
- No link to the mucroom : xmpp:psi-dev@conference.jabber.ru?join
- In News section, links are dead, remove links (only "1.3 released!" works)
- Update the forum link to https://groups.google.com/group/psi-users
- http://psi-im.org/ is redirected to https://psi-im.org/index.php, it will be better to have only https://psi-im.org/

On https://psi-im.org/development/
- http://psi-im.org/wiki/Road_Map (Dead) and https://github.com/psi-im/psi/issues/milestones is nothing.
- Psi Issues page -> issue page
- Mailing list (Dead)
- Development Guidelines -> Doxygen?
- Wiki (Dead) -> There is now https://github.com/psi-im/psi/wiki
- Nightly Builds (Dead) -> And there are not "official nightly builds"
- Delta Project (Dead) -> http://jblog.andbit.net/2017/02/26/delta-xmpp-project-shutdown/
- Delta mailinglist (Dead)

On https://psi-im.org/about/
- http://xmpp.org/ -> https://xmpp.org/
- http://psi-plus.com/ -> https://psi-plus.com/
- http://flyspray.org/ -> https://www.flyspray.org/
- http://sleekbot.googlecode.com/ -> https://code.google.com/archive/p/sleekbot
- http://delta.affinix.com/qca/ -> https://userbase.kde.org/QCA
- Justin, Kevin and Sergey part need an update
- Justin real website: http://andbit.net/  // email in README
- Kevin real website: http://doomsong.co.uk/
- Michail, Hal and Maciek websites are dead

One more to be removed, please note that:
- plus.google.com will be deleted in few days.

**Comment by tehnick** [comment]
> On https://psi-im.org/about/

Fixed.

**Comment by tehnick** [comment]
> On https://psi-im.org/development/

Fixed.

**Comment by tehnick** [comment]
> On https://psi-im.org/

Fixed everything that makes sense.
