### ISSUE TITLE
OMEMO encrypted files are displayed as text beginning with aesgcm://

### ISSUE THREAD

**Issue by cweiske** [psi-im/psi#406]
When I receive a file, encrypted via OMEMO, Psi+ displays it as text message starting as follows:

```
aesgcm://jabber.ru/upload/7e92a9630....
```

The file is not downloaded, nor is it shown when it's an image.

According to https://github.com/psi-im/plugins/blob/master/generic/omemoplugin/changelog.txt this has once been working.

Chat today:
> [21:39:31] &lt;Tehnick> cweiske: confirmed. It is broken now... =( 
> [21:41:06] &lt;Tehnick> cweiske: there were many changes related to processing of messages in chats. Probably they have broke such kind of links.

**Comment by Neustradamus** [comment]
I had same problems with a Gajim user some weeks/months ago.

"aesgcm://www..." and "file:///C:/Users/XXXX/AppData/Local/Psi+/aesgcm_files/..."

**Comment by Neustradamus** [comment]
Always here, confirmed today with 2 people, one with Conversations and one with Psi+:
```
[XX:XX:XX] ***  Encryption Enabled
[XX:XX:XX] <contact> aesgcm://MYDOMAIN:PORT/upload/XXXXXXXX/XXXX.jpg#XXXX
[XX:XX:XX] ***  Encryption Disabled
[XX:XX:XX] <contact> file:///C:/Users/user/AppData/Local/Psi+/aesgcm_files/XXXXXXXXXXXXXX.jpg
```

Unencrypted file is ok.

Linked to: https://github.com/psi-plus/main/issues/722

**Comment by beelze** [comment]
Confirming. 
Seen the same aesgcm://* message when sending to Psi (can't paste full text because of non-working clipboard copy)

**Comment by stigger** [comment]
Works as intended. The aesgcm:// link arrives, then the file gets downloaded and decrypted, and then the local file is displayed as the file:// link.

**Comment by Moarc** [comment]
Not anymore. After scrapping the OMEMO plugin and moving OMEMO support to the main codebase, this remains unimplemented.

**Comment by Ri0n** [comment]
> moving OMEMO support to the main codebase
What is this about?

**Comment by Moarc** [comment]
Am I misunderstanding? I thought OMEMO support was no longer a plugin.

**Comment by Ri0n** [comment]
It's http upload plugin which is moved to iris. 
OMEMO is still implemented as a plugin.

**Comment by Ri0n** [comment]
Ok, I'll check that.
