### ISSUE TITLE
Options search form is tremendously slow. Needs optimization.

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#409]
It is not easy to found an option in "Shortcuts" and "Advanced" options.
Can you add a search form for each?

**Comment by Vitozz** [comment]
Maybe we could close this ticked because it was fixed in d225de33bd3c07e7dc39014802ba83766be73109

**Comment by Neustradamus** [comment]
No, there are no change on last build.
No search form here...

**Comment by tehnick** [comment]
Options --> Advanced --> Flat --> now you may use filter
