### ISSUE TITLE
[GitHub] Manage topics

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#421]
Please add topics for all Psi/Psi+ projects for have a better visibility, examples:
- xmpp
- xmpp-client
- qt
- qt5
- collaboration
- cross-platform
- otr
- omemo
- e2e-encryption
- file-transfer
- chat
- chat-application
- instant-messaging

**Comment by tehnick** [comment]
Done.

**Comment by tehnick** [comment]
Now it will be much easier for Russian government to find our project and to ban it due to implemented e2e-encription... =)

**Comment by Neustradamus** [comment]
Thanks for changes, you can see for the last too ^^
The project is already known since a very long time

**Comment by tehnick** [comment]
@Neustradamus 
There should not be too much tags (topics). Current amount of them is optimal.

**Comment by Neustradamus** [comment]
I speak for other without tags

**Comment by tehnick** [comment]
> I speak for other without tags

There is no reasons to add tags for them.
