### ISSUE TITLE
Sometime captcha windows become unclosable

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#422]
No idea when. I just got office I see this captcha window which I can't close.
I joined captha protected conference from home but not at office (other resource)

Doesn't matter what I presss ok/cancel/close button. It just stay on top.
related xml console log is run away.
there is nothing written to ~/.xsession-errors on any action and anyway it's likely with wayland common stdout file has another name..

**Comment by Neustradamus** [comment]
Linked to: https://chatlogs.jabber.ru/psi-dev@conference.jabber.ru/2018/05/17.html#15:14:08.217719

**Comment by Ri0n** [comment]
likely fixed with 46187b885657b4e4c80b58b7b16e1039d41fafec
