### ISSUE TITLE
[Website] XMPP logo update from 2017

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#429]
Can you update the XMPP logo by the new XMPP logo?
-> https://psi-im.org/content/xmpp.png

XMPP logo: https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

More changes for website: https://github.com/psi-im/psi/issues/405

**Comment by tehnick** [comment]
Done.

**Comment by Neustradamus** [comment]
@tehnick: Can you update a new time in the websites and other places, in the code?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png
