### ISSUE TITLE
Can't force Psi 0.15 to use my aspell dictionaries

### ISSUE THREAD

**Issue by kiav** [psi-im/psi#43]
Psi 0.15
Windows 8 32 bit

Dictionary files 

ru.dat 
ru_phonet.dat 
ru.multi 
ru.rws 
russian.alias

in C:\Program Files\Psi\aspell

LANG environment variable (user, not system) is set to ru_RU (tried also just ru)

But spell check checkbox is disabled and options.ui.spell-check.enabled is false
When I delete setting for LANG env variable Psi can check spelling but uses english dictionary.

The last time when my settings were used by Psi correctly:

Psi 0.14
Vista 32 bit

**Comment by Ri0n** [comment]
Currently we prefer hunspell for windows and linux. Psi also has multilanguage support for it.

**Comment by Ri0n** [comment]
This bug seems to be very outdated and out of interest. I'm closing it.
