### ISSUE TITLE
When a person sends messages in MUC room or normal chat, there is an autoscroll

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#430]
When a person sends messages in MUC or normal chat, there is an autoscroll.

Example: We are at top (we read the text) in the window, the person sends a new message, I am now at bottom.

It will be nice to have not this or an option for enable/disable autoscrolling.

**Comment by wadealer** [comment]
AFAIK we already have this option. Check Ext. Opt. plugin

ср, 27 Фев 2019, 7:28 Neustradamus <notifications@github.com>:

**Comment by tehnick** [comment]
@Neustradamus , you forgot to mention that this bug is present only in basic version of Psi+ (without webkit or webengine).

**Comment by Neustradamus** [comment]
@wadealer: I have never seen this option in Extended Options plugin before, I have disabled it for "Chat" tab, there is not for "Groupchat".

The problem is same for chat.

@tehnick: I have not tested with WebKit/WebEngine, I can not confirm if it works.

**Comment by Ri0n** [comment]
fixed with 45e2a9ff019f6635fac84d6fd4571819dec82204

**Comment by Ri0n** [comment]
reproduced with disabled
