### ISSUE TITLE
On a contact: Send Message -> Send Message: No Key

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#432]
Step to reproduce this bug:
Env.: Options -> Extended Options plugin -> Menu -> "Enable single message" enabled

On a contact -> "Send Message" -> "Send Message"
Enter a message and "Send"
The first message is sent.

Do it same a new time:
The message is not sent, there is a "No key" box.
-> https://i.ibb.co/44VXsjx/psi-plus-normal-message-send-test-after-one-sent.png

The contact has received the first message.
He can try "Quote" or "Reply" ("Chat" or "Close" have not a problem of course)
He enter the message and "Send"
The message is not sent, there is a "No key" box.
-> https://i.ibb.co/KjMhb6V/psi-plus-normal-message-received-reply.png

Done on the same client with 2 JIDs.

This problem is linked to OpenPGP, OMEMO, Toggle Encryption.

Note: This problem was previously here for "Open Chat Window"; I had informed a long time ago the plugin dev who has solved for this part.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/psi-im/psi/issues/318
- https://github.com/psi-im/psi/issues/433

**Comment by Neustradamus** [comment]
In my screenshot database, it is in tab here and it was solved:
- https://i.ibb.co/S0Kr31T/psi-omemo-bug-nokey-openpgp.png

I think it can be done in "Send Message" part too.

**Comment by tehnick** [comment]
> Options -> Extended Options plugin -> Menu -> "Enable single message" enabled

It is time to remove this feature from Psi.

@Ri0n  What do you think?

**Comment by Ri0n** [comment]
I remember some users reported they use Psi only because it has this feature.

**Comment by tehnick** [comment]
> I remember some users reported they use Psi only because it has this feature.

They may stay with old versions of program.

**Comment by tehnick** [comment]
I did not saw any other xmpp client which support this feature. All of them use standard chats for displaying such messages.

**Comment by Ri0n** [comment]
Another reason is it's a way to send to multiple recipients. Doesn't matter if they are in your contact list of not.
Even so, I'm Ok to move this to a plugin

**Comment by tehnick** [comment]
> Another reason is it's a way to send to multiple recipients. Doesn't matter if they are in your contact list of not.

So, this is feature specially for spammers. I see.

> I'm Ok to move this to a plugin

Heh, it requires much more time than just removing code...

**Comment by tehnick** [comment]
After discussion in groupchat we decided to leave this message window feature as is, but remove OpenPGP function from it.

**Comment by tehnick** [comment]
96911cf2698c8662d947663f60bd44e0f43c04c9
