### ISSUE TITLE
[OMEMO] No icon for enable or disable in normal message (Only Toggle Encryption icon)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#433]
In "Send Message" or "Send Message to Group" or "New Blank Message" windows:
-> https://i.ibb.co/tPC1sBs/psi-plus-normal-message-window.png

There is not OMEMO icon only Toggle Encryption.

To have the window:
- On a contact: Send Message -> Send Message
- On XMPP account: New Blank Message
- On a group of an XMPP account: Send Message to Group
- In "Menu Items" for "Buttons"/"Show contacts"/"Event notifier" toolbars: New Blank Message

Linked to https://github.com/psi-im/psi/issues/318

**Comment by tehnick** [comment]
Fixed by removing of OpenPGP button from this deprecated dialog window.

**Comment by Neustradamus** [comment]
@tehnick, @Ri0n:
Little recall: The "deprecated" dialog window is used for all system messages etc.

**Comment by tehnick** [comment]
Yes, notifications systems should be re-considered too. In a far perspective...
