### ISSUE TITLE
Double priority informations

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#449]
Env.:

Options -> Plugins -> Extended Options Plugins -> Options -> Chat
- Show status changes
- Show status priority

Options -> Plugins -> Extended Options Plugins -> Options -> Groupchat
- Show status changes
- Show status with priority

Look chat (normal chat) window or groupchat (muc room) window, example:
*** USERNAME is now STATUS: [YYY] [YYY]

**Comment by Vitozz** [comment]
Is this a bug? And why report about plugin in this tracker?

**Comment by Neustradamus** [comment]
Yes it is a bug, twice informations ^^

**Comment by Vitozz** [comment]
Did you see duplicates of status messages in chatlog? Groupchat log and chat log are not the same log. Each log has possibility to show status messages.

**Comment by Vitozz** [comment]
I've made some investigations and can't reproduce this "bug".
Messages from chat
[16:07] *** KukuRuzo is now Online
[16:07] *** KukuRuzo is now Offline: Logged out
[16:07] *** Contact has been switched: JID
[16:07] *** KukuRuzo is now Away
Messages from groupchat
[16:08] *** Vitozz (JID) has joined the room as a moderator and an administrator and now is Away
[16:08] *** Vitozz is now Not Available
[16:09] *** Vitozz is now Do not Disturb
[16:09] *** Vitozz is now Online
[16:09] *** Vitozz (JID) has left the room
options are
http://pix.academ.info/img/2019/09/19/8ff227a406678647b97b2829d4f240d3.png
for chat
http://pix.academ.info/img/2019/09/19/bc62cea581f46bef7c9e41c05c62a445.png

**Comment by Neustradamus** [comment]
[XX:XX:XX] *** XXX is now Not Available: Автостатус (неактивен) [30] [30]
[XX:XX:XX] *** XXXX has left the room
[XX:XX:XX] *** XXXX has joined the room as a participant and a member and now is Online
[XX:XX:XX] *** XXX is now Online: [50] [50]
