### ISSUE TITLE
Psi doesn't send final "unavailable" presence on program exit

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#451]
It just closes socket.

*OS:* Linux

*Psi Version:* 761f89319b220a78c32d653d57d736aa534dee90

related part of code in `PsiAccount::logout` which is called on program exit.

```c++
    if (fast) {
        d->finishLogout();
    } else { // let iris queue write all the stuff
        d->logoutTimer->start();
    }
```

the `d->finishLogout();` logout kills socket before it's able to send the presence.
`d->client->setPresence(s);` doesn't send presence instantly. Instead it's handled asynchronously somewhere in QCA sasl layer. So it's hard to say when exactly the outgoing data will be ready and eventually sent.

To solve this we have to modify layered stream state machine to add kind of `flush()` to stream. And as a workaround we can defer the `d->finishLogout();` call, but the delay doesn't look to be predictable.

**Comment by tehnick** [comment]
[Temporary workaround](https://github.com/psi-plus/main/commit/f2e2992873304b04a25dac0dc0600c7e67e5bc1b) works fine for me.

**Comment by Ri0n** [comment]
the workaround was applied so closing
