### ISSUE TITLE
it'd be nice if psi-im was more avatar-oriented alike gajim and more "mainstream" instant-messengers and stuff

### ISSUE THREAD

**Issue by anontests** [psi-im/psi#456]
it'd be nice if psi-im was more avatar-oriented alike gajim and more "mainstream" instant-messengers and stuff. 

and i'm talking about default. alike gajim, and stuff.  or at least in a default mainstream version. there can be a minimal alternative version or download; if everyone cares that much. 

gajim is nice because it's cross-platform and it looks mainstream. 

but gajim is sorta broken and has issues and not some features alike psi-im. 

other stuff you don't have to read; mods you can remove it; i can remove it if asked:: 

by the way. also. the gajim dev team is tired of me, tells me they can't do anything, then just sorta ignores me apparently. 

so. again. i'm sorta hoping that psi-im could be more avatar-oriented; alike gajim; and become the mainstream instant messenger thing. 

i still believe jabber xmpp can succeed as an ultra-mainstream thing. as in over 100,000,000 users or even over 1,000,000,000 users. even with 1 program alone. i just think we haven't seen it yet. google talk was very close. but i don't think that has to be the only thing. 

certainly better than alternatives such as discordapp where you have none of the features and options and everything's broken and out of your control. and everyone loves it. i don't understand. anyway. 

i still think psi-im has an extremely good chance of being a mainstream thing; or at least mainstream to me; since i'd have something i can get behind; and promote; and use. 

irc is sorta a pain because mods. as usual. they can get mad at you, give you a "punishment", and temporarily ban you, maybe even permanently ban you. a lot of things block "open" proxies, you'd be paying freaking money just to not get banned by buying a proxy; and you're not even sure if that works; and; basically; it's still a pain. 

you could make your own thing but that's also a pain. i also have concern about government interference and what not. it's not so much doing anything illegal. so much as government losing it and over-reacting over nothing.

i actually can't use skype because it forces you to buy a cell phone to use it to spy on you and link it to you and your accounts and stuff. 

discordapp is a pain alike i said. 

i don't want to be forced to use discordapp or anything because i can't promote any better alternative left anymore. 

no mainstream cross-platform anything. 

i mean. i don't mind it's not "mainstream". but. i'd like to be able to promote something that can really compete and become "mainstream". 

gnu-linux android cross-platform would be nice to but that's a different story. 

so. anyway. again. 

too long; didn'tread: 

it'd be nice if psi-im was more avatar-oriented alike gajim and more "mainstream" instant-messengers and stuff. 

please help me. 

anyway. 

i hope this helps. 

take care.

**Comment by Ri0n** [comment]
it's already
