### ISSUE TITLE
it'd be nice if we could change the text size in a window without having to use ctrl+mouse-wheel

### ISSUE THREAD

**Issue by anontests** [psi-im/psi#457]
it'd be nice if we could change the text size in a window without having to use ctrl+mouse-wheel. 

i'm not sure if it's possible to do it already. if it is. then. i know it must be simple. i just can't find it. 

other stuff you don't have to read: 

i have someone i want to contact on jabber-xmpp. but they can't see the text because it's too small. 

gajim has no way of making the text bigger. apparently. 

psi-im can only make text bigger by using ctrl+mouse-wheel. 

some computers and most laptops don't have a mouse-wheel. 

my thinkpad keyboard has a mouse-wheel button that acts as the 3rd middle-button; but i can't use it as a mouse-wheel for this. 

there's also the idea of using the "scroll" key. but i don't have "scroll" on any of my laptop keyboards. apparently seen as "useless". ironically enough. 

you can also apparently go into windows settings and activate "2 finger" scrolling or something. but it's still a pain. 

too long; didn't read: 

it'd be nice if we could change the text size in a window without having to use ctrl+mouse-wheel. 

i'm not sure if it's possible to do it already. if it is. then. i know it must be simple. i just can't find it. 

please help me. 

anyway. 

i hope this helps. 

take care.

**Comment by Ri0n** [comment]
font size is in settings
