### ISSUE TITLE
View>Show XXX do not work at all in Psi 1.3

### ISSUE THREAD

**Issue by liar666** [psi-im/psi#460]
Hi,

Whatever the status (Checked/Unchecked) of View>Show Offline/Hidden/Agent/Self, everything is always displayed.

See for example the attached picture, where Offline Contacts display is disabled, but they still appear in the list
![psi_bugs](https://user-images.githubusercontent.com/3216927/59771984-37847000-92ab-11e9-99ab-0f0247162b13.png)

**Comment by Ri0n** [comment]
Could retest it with a nightly build? https://sourceforge.net/projects/psiplus/files/Windows/Personal-Builds/

**Comment by Ri0n** [comment]
ah it's Linux. we have Ubuntu ppa https://launchpad.net/~psi-plus/+archive/ubuntu/ppa

**Comment by Ri0n** [comment]
no feedback. not reproducible
