### ISSUE TITLE
Appearance dialog is incomplete

### ISSUE THREAD

**Issue by liar666** [psi-im/psi#461]
In Options > Appearance, it is possible to change the font size of various things, like the Roster window. This works perfectly.

Unfortunately, the buddy's avatar picture size remains the same whatever the font size.

As a consequence, the Roster window always occupies the same size on the screen and it is not possible to display more buddies without changing the Roster window size.

Also, when the Roster window it at its maximum, one cannot display any more buddies at all.

Also due to bug #156, one cannot remove buddies from the list.

It would be great if you could manage to resize the Buddy's picture with respect to the font selected or, at least, to propose an option to resize the avatar picture, or more simply an option to zoom the internal content of the Roster (font + image synchronously), so that one can find a configuration were one see the whole list of online buddies at once on the screen, whatever the number of buddies and/or the screen resolution.

Thanks

liar666

*OS:* XUbuntu 19.04

*Psi Version:* 1.3

**Comment by Ri0n** [comment]
try scroll the contact list with mouse or you ca enable scrollbar in roster settings.
avatar settings are also available in roster settings.
The issue #156 you referenced is likely unrelated to what you are saying.
