### ISSUE TITLE
core dump on NetBSD amd64

### ISSUE THREAD

**Issue by teknokatze** [psi-im/psi#465]
A potential follow-up to #463 

Once the project is build on NetBSD 9 (8.99.48) amd64, it core dumps once any kind of interaction with the GUI is done. Below: Open status dropdown, select "online".

I have a ktruss log of this and I can provide more information if you tell me what could be selectively useful for you.

```
[20190716 19:05:31] W:QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ng0' (unknown:0, unknown)
[20190716 19:05:41] W:libpng warning: iCCP: known incorrect sRGB profile (unknown:0, unknown)
[20190716 19:05:45] W:Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
 (unknown:0, unknown)
[1]   Abort trap (core dumped) psi
```

**Comment by Ri0n** [comment]
Please start in gdb add stack trace to this issue when you have one

**Comment by Ri0n** [comment]
no feedback. nobody else reported bsd crashes. closing

**Comment by tehnick** [comment]
BTW, in FreeBSD Psi+ builds (see them as builds of Psi from master branch) work fine.
