### ISSUE TITLE
two user all online,but can not get the message , when online again ,that will get message

### ISSUE THREAD

**Issue by spikezk** [psi-im/psi#466]
<two user all online,but can not get the message , when online again ,that will get message.
This issue from psi 1.2version ,but 0.15 version is good>

*win10 ,or xp ,or win7*

*1.2,1.3,1.4*

XML log (you can find it in account's context menu)
```
paste your xml log here
```

stdout (terminal log)
```
paste your terminal log here
```

In case of app crash please provide back trace (start debug version in gdb).

You can always ask for help in xmpp:psi-dev@conference.jabber.ru?join

**Comment by Ri0n** [comment]
with OpenFire server?

**Comment by spikezk** [comment]
yes，the server is openfire

**Comment by Ri0n** [comment]
Try to update your server to 4.4.0 version. I tested it yesterday and it seems to work fine.
If server update is not an option then disabled Stream Management will solve your problem.

**Comment by spikezk** [comment]
thanks very much，I had updated server to 4.4.0, and I will follow this , if this arise again， I will let you know.
