### ISSUE TITLE
Word highlighting not playing sound anymore?

### ISSUE THREAD

**Issue by lminiero** [psi-im/psi#489]
For the past few years, I've used the "word highlighting" quite extensively as a way to be quickly notified about relevant events. Psi is used as a support tool in some scenarios, where we join multiple Jabber rooms at the same time: "word highlighting" allows us to be notified right away when something we need to be aware of is reported, and respond. Up until recently, the occurrence of a highlighted word also triggered a sound, which made the process much more effective for us: this doesn't seem to happen anymore. Last time I used Psi in this context was about three months ago, but unfortunately I can't recall which version of Psi was available on my machine at the time (probably the one in Fedora 28, as I did upgrade recently to 30). Was there any recent change that may have caused this? I went through the options, but couldn't find any setting that might have an impact on the feature: the "word highlighting" section doesn't have a sound-related knob, and the same is not in the list of sounds that can be configured in the "Sound" tab.

Thanks!

*OS:* Fedora 30

*Psi Version:* 1.4 dev (`psi-1.4-1.fc30.rpm`)

(Not sure logs asked by the template are needed for this? In case, please let me know and I'll oblige.)

**Comment by Ri0n** [comment]
Hi Lorenzo,
If sounds are enabled (options.ui.notifications.sounds.enable) and your current status is not DND and options.ui.notifications.sounds.silent-while-away option is not set while you are in other away-like statuses then you should here the sound.
Path to the sound file is computed like `<PREFIX>/share/psi/<sound path from ui>` which is likely to be resolved into either `/usr/share/psi/sound/chat1.wav` or `/usr/share/psi/sound/chat2.wav` by default.

Then it will try to take your player from settings or if not set/found it will try either `aplay -q` or `play` to play the sound.

This logic wasn't changed for years afaik and it works for me.

Please check all the options and paths. Start from just clicking "play" button on corresponding sounds in the settings dialog, then check you see your word highlighted in the chat and then check other sound options.

**Comment by lminiero** [comment]
Hi Sergey,

thanks for the quick answer! After I opened the issue, I did get sounds for some of those events, but not for others. I haven't yet figured out if it's related to whether Psi is the active application or not, which is what I initially thought about, as I didn't get the sound also when I was on a different workspace. I'll have a look at the options you mentioned, and in case they don't seem to help, try to derive a pattern for the problem (if there is a bug at all, that is, as it may very well be my setup!).

**Comment by Ri0n** [comment]
Wait a second. You are a developer of Janus server, correct? I recently had a project based on it :)
Particularly I partially integrated Amazon Speech To Text there but then I was forced by our managers to migrate to another media server. It was nice anyway :)
Now I work in one team with Gustavo Garcia (very likely you know him)

**Comment by lminiero** [comment]
Yes that's me! Small world :smile: 
Too bad that you had to move away from it, but I hope it was a nice experience!
I do know Gustavo, even though only online: we haven't met in person yet, hopefully that will happen someday.

**Comment by lminiero** [comment]
I can't seem to be able to replicate it anymore: I do get the sound even when I'm actually using Psi, so that wasn't it either. As such, I'm pretty confident it was an issue related to my own setup. Sorry for the noise, and keep up the great work!
