### ISSUE TITLE
MUC Room avatar/picture/logo not showed in roster if connected, it is generic icon

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#496]
MUC Room avatar/picture/logo not showed in roster if connected, it is generic icon

Example:
- https://i.ibb.co/44nw17s/psi-plus-avatar-online-offline-muc-room-diff-in-roster.png

Mouse on MUC Room in roster:
- https://i.ibb.co/zZhGD2M/psi-plus-mouse-on-mucroom-in-roster-avatar-showed-but-generic-icon-in-roster.png

**Comment by Ri0n** [comment]
fixed
