### ISSUE TITLE
MUC Room avatar/picture/logo in vCard but not showed in MUC Room at bottom mic right

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#497]
MUC Room avatar/picture/logo in vCard but not showed in MUC Room at bottom mic right

Example:
- https://i.ibb.co/M591c27/psi-plus-avatar-muc-room-in-vcard-but-not-always-here-at-bottom-mic-right.png

No problem with an another XMPP client, it is showed correctly.

**Comment by tehnick** [comment]
It was problematic png file produced by GIMP.

**Comment by Neustradamus** [comment]
GIMP does not export perfect PNG?

Have you contacted GIMP team for solve the problem?

**Comment by Neustradamus** [comment]
Note: It is strange that it is good in vCard.
