### ISSUE TITLE
Plugins don't show up on Kubuntu 19.10

### ISSUE THREAD

**Issue by thewoose** [psi-im/psi#498]
Hi,
I have the plugins installed and see them in /usr/lib/psi/plugins.  I even tried copying them to lib64 but to no avail.  When I click the Plugins tab in the options menu, nothing happens.  It it nothing but a big blank box.  I've had this problem on two different PCs.  There is no config file or anything which might allow me to point it to where they are.  But it just refuses to display the plugins.

**Comment by tehnick** [comment]
1) Which version of Psi IM do you use? Tarball with plugins should should be exactly the same version as tarball with Psi IM.
2) Have you tried Psi+? This is development version of Psi IM with rolling release development model....

**Comment by tehnick** [comment]
No response
