### ISSUE TITLE
Outdated Psi Discussion Room option in help menu

### ISSUE THREAD

**Issue by The-Steel-Talon** [psi-im/psi#501]
Problem:
conference.psi-im.org    -----> Does not exist.
I have talked about this at psi-dev@conference.jabber.ru with VitoZz.
In the Help section of context menu of PSI there is an option "Join Psi Discussion Room (online)".
This option is outdated.

OS:
ArchLinux 5.4.22-1-lts x86_64

Psi Version:
Psi v1.4-dev (2019-10-07)
https://i.imgur.com/EpDSiws.png

**Comment by Ri0n** [comment]
We do not plan to release patches for this old version.
New one has it fixed already
