### ISSUE TITLE
IDN2008 instead of IDN2003 // Use libidn2 instead of libidn (or other)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#504]
UPDATE: libstringprep is here, done by @rockdaboot : https://gitlab.com/libidn/libidn2/-/issues/28#note_321827403

Can you see for migrate to libidn2 or other?
- https://www.gnu.org/software/libidn/
- https://github.com/libidn/libidn2
- https://gitlab.com/libidn/libidn2

Current problems:
- We can't migrate to libidn2 since it doesn't have xmpp profile: https://gitlab.com/libidn/libidn2/-/issues/28 + https://libidn.gitlab.io/libidn2/manual/libidn2.html#Stringprep-and-libidn2
- We have to use PRECIS spec but there is no libraries implementing it in C/C++
- Psi sometimes suffers from invalid jids encoding with some exotic chars in jids (node)
- There is very basic PRECIS implementation in gnupg or gnutls (I don't remember exactly) but it doesn't cover everything required for Psi

Solution 1 and the best, I think:
@jas4711: Can you export "stringprep" from libidn?

Like:
- https://github.com/processone/stringprep
- https://github.com/ongres/stringprep
- https://github.com/sfackler/rust-stringprep
- https://github.com/edipermadi/stringprep-js
- https://github.com/znerol/Stringprep
- https://github.com/steakknife/stringprep
- https://github.com/ubiety/Ubiety.Stringprep.Core
- https://metacpan.org/pod/Unicode::Stringprep
- https://github.com/xdg-go/stringprep
- https://github.com/horde/Stringprep
- https://github.com/konsultaner/saslprep-dart
- https://github.com/reklatsmasters/saslprep
- https://github.com/ronram5126/dart-stringprep
- https://github.com/astro/node-stringprep
- https://github.com/Porges/stringprep-hs
- https://github.com/Arachnid/stringprep-js
- https://github.com/pihi/stringprep
- https://github.com/DanielOaks/go-idn
- https://github.com/gitpan/Unicode-Stringprep
- https://github.com/cfaerber/Unicode-Stringprep
- https://github.com/hrydgard/nodeprep
- https://github.com/lloydwatkin/node-stringprep-icu
- https://github.com/treacheroustalks/stringprep-app
- https://github.com/tombentley/saslprep
- https://github.com/sabracrolleton/saslprep

For PRECIS, there are:
- https://bitbucket.org/sco0ter/precis/src/master/
- https://github.com/tom--/precis
- https://github.com/hatukanezumi/Unicode-Precis
- https://github.com/hatukanezumi/Unicode-Precis-Preparation
- https://github.com/NineFX/bs-precis
- https://github.com/byllyfish/precis_i18n
- https://github.com/SwiftBlues/PRECISSwift
- https://github.com/eloquent/precis-js
- https://github.com/Florob/precis-rs
- https://github.com/hannesm/precis

ICU:
- http://site.icu-project.org/
- http://userguide.icu-project.org/strings/stringprep#TOC-XMPP-Profiles

**Comment by Ri0n** [comment]
not sure if any of these links does any help

**Comment by Neustradamus** [comment]
Ri0n: I specify all about the libidn2 problem and stringprep/saslprep and precis librairies.

For Psi, I think there is ICU instead of libidn2, no?

**Comment by Ri0n** [comment]
icu maybe. It's already linked with qt on some systems

**Comment by Neustradamus** [comment]
@Ri0n: https://gitlab.com/libidn/libidn2/-/issues/28#note_321827403

There is "libstringprep" now, can you look and confirm that it works with libidn2 + libstringprep?

The author will create a final libstringprep version.

**Comment by Neustradamus** [comment]
@Ri0n: @rockdaboot waits news from the Psi project to release the libstringprep 1.0.

**Comment by rockdaboot** [comment]
In fact, I would release libidn 1.36 which provides libidn and libstringprep. Downstream likely need to adjust their package recipes to include both libraries.

**Comment by Ri0n** [comment]
> In fact, I would release libidn 1.36 which provides libidn and libstringprep. Downstream likely need to adjust their package recipes to include both libraries.

We need just stringprep xmpp profile. IDN stuff is already implemented in Qt.

**Comment by rockdaboot** [comment]
@Ri0n Libstringprep just holds the profiles, the stringprep functions/API and some NFKC code which is needed for stringprep.

**Comment by Neustradamus** [comment]
@Ri0n: Can you look asap?
With this, @rockdaboot can release an official build.

**Comment by rockdaboot** [comment]
The decision has been made to not create a new library.

**Comment by Neustradamus** [comment]
@rockdaboot: Can you export me an archive?
I have not download it, thanks in advance.

**Comment by Ri0n** [comment]
@Neustradamus, I can't switch to this task right now. be patient.
Since libidn1 is somewhat obsoleted and already removed from some distros, I don't see a problem to incorporate some part of libidn1 sources directly to iris library. especially if libstringprep is isolated enough.

**Comment by jas4711** [comment]
Which distro has libidn removed? Adding a new libstringprep library should be more work than just re-enabling libidn for psi though. New build parameters to drop non-stringprep parts of libidn from the build would be considered, if size issues is a concern.

Note that stringprep is also obsolete. Code should be upgraded to precis framework. I understand some standards may be lagging though.

/Simon

**Comment by Ri0n** [comment]
> Which distro has libidn removed? 

I just heard talks how distro maintainers pushed package maintainers and upstream to migrate to libidn2 as soon as possible since the libidn1 is going to be removed soon. 
IIRC it was Fedora last time.

So I believe it's already removed from some distros which care less about backward compatibility.

**Comment by Ri0n** [comment]
I made Conan recipe to build stringprep either with Visual Studio or on Linux.
https://github.com/Ri0n/conan-stringprep/
I haven't tried to use the lib though.

**Comment by Ri0n** [comment]
stringprep is now bundled to libiris https://github.com/psi-im/iris/tree/master/3rdparty/stringprep
