### ISSUE TITLE
TLS S2S problems / No reply from the MUC Room

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#505]
TLS S2S problems -> XMPP clients have not error.

When an user@xmpp1.tld tries to join a mucroom@conference.xmpp2.tld, it is not possible and the XMPP client has not an error.

Can you add a dialog window after a timer (timer configuration in options) which inform that it is not possible to join the room because TLS S2S problems, server has been detected but no reply from.

**Comment by Ri0n** [comment]
fixed

**Comment by Neustradamus** [comment]
What is the option in advanced options for the timer choice?

**Comment by Ri0n** [comment]
hardcoded 30 secs. as soon as we need an option, we will add it.

**Comment by Neustradamus** [comment]
@Ri0n: There is a problem, when we try to join a room which has the "30s" window (after or several hours after):
- https://i.ibb.co/JBsC0tT/psi-plus-error-window-dialog-you-are-in-or-joining-this-room-already.png

In the same time, please add an option for the timer choice in advanced options (default value 30s"
