### ISSUE TITLE
Importing history fails due to too many open files

### ISSUE THREAD

**Issue by luke-jr** [psi-im/psi#507]
After upgrading Psi, it wanted to import my history. But it fails, because it tries to have all of them open at the same time, which exceeds the open-file limit.

P.S. I assume the plaintext .history files will continue to be updated for CLI grepping?

**Comment by Ri0n** [comment]
known problem. probably we already have a report for it.

**Comment by Ri0n** [comment]
You can use similar approach for grepping https://unix.stackexchange.com/questions/291062/sqlite-command-line-how-do-you-pipe-output-to-a-unix-utility

**Comment by Ri0n** [comment]
```
sqlite3 ~/.local/share/psi/profiles/default/history/history.db "select * from events" | grep coronavirus
```

**Comment by Neustradamus** [comment]
There is a problem in SQL history, I have published one year ago:
- https://github.com/psi-im/psi/issues/411

When we want to search "test" for example, you start to write "t", the client does not respond.
Wait several seconds/minutes, and you can write now "e", wait again...

It must be better if search works only after we have written the complete search and pushed on enter button.
