### ISSUE TITLE
Won't remember password for jid on LinuxMint 19.3 [keyring issue?]

### ISSUE THREAD

**Issue by motivemachine** [psi-im/psi#513]
Just installed Psi+ from the Ubuntu PPA, and it doesn't seem to store any passwords. After restarting the program, a popup appears for `Wrong account password, please input password for jid@server.com`

After starting the program from the terminal I get several errors related to saving password in keyring [see below]. 

Simply unselecting ` Use system keyring manager` in the options menu solves the problem. I don't mind using Psi+ like that but I thought someone might know if this is a Psi issue or a gnome-keyring problem.  

*OS:* Linux Mint 19.3

*Psi Version:* v1.4.1073

stdout (terminal log)
```
[20200419 12:06:04] W:KeyChain error=5 (unknown:0, unknown)
[20200419 12:06:17] W:KeyChain error=5 (unknown:0, unknown)
[20200419 12:06:17] privacy.cpp: Error in lists receiving. (unknown:0, unknown)
[20200419 12:06:33] W:Failed to save password in keyring manager (unknown:0, unknown)
[20200419 12:06:33] W:Failed to save password in keyring manager (unknown:0, unknown)
[20200419 12:06:33] privacy.cpp: Error in lists receiving. (unknown:0, unknown)
[20200419 12:07:02] privacy.cpp: Error in lists receiving. (unknown:0, unknown)

```

In case of app crash please provide back trace (start debug version in gdb).

You can always ask for help in xmpp:psi-dev@conference.jabber.ru?join

**Comment by tehnick** [comment]
Hi,

> I thought someone might know if this is a Psi issue or a gnome-keyring problem.

Yes, this is a known problem with QtKeychain library. See: https://github.com/frankosterfeld/qtkeychain/issues/151

If `libgnome-keyring0` package is still present in Linux Mint 19.3, you may just install it and all will work fine. If not then `Use system keyring manager` will not work in your DE.

**Comment by motivemachine** [comment]
Ok good to know. `libgnome-keyring0` appears to already be installed. I'll just keep not using the system keyring for now.

**Comment by Ri0n** [comment]
@motivemachine could you try latest master version? I did some fixes yesterday. They should help
