### ISSUE TITLE
A better client detection for icons

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#514]
Currently there is a problem with some clients.

Example for QIP:
In client_icons.txt, there is:
> qip qip

qip is detected no problem
2010.qip.ru is not detected

By default, if no exception in the file of course that "qip qip" must be used for qip and 2010.qip.ru without nothing more.

**Comment by Ri0n** [comment]
qip was fixed today

**Comment by Neustradamus** [comment]
It is an example.
And:
"qip qip" must be the only solution for qip and 2010.qip.ru.
The goal is to have simple file.
