### ISSUE TITLE
Can you add Conv6ations icon?

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#516]
Conv6ations:
- https://dev.sum7.eu/sum7/Conversations/-/blob/develop/art/logo.png

**Comment by genofire** [comment]
![Convers6ation icon squared](https://dev.sum7.eu/sum7/Conversations/-/raw/develop/art/new_logo.png)
Or the rounded version: ![Convers6ation icon rounded](https://dev.sum7.eu/sum7/Conversations/-/raw/develop/art/new_logo_round.png?inline=false)
https://dev.sum7.eu/sum7/Conversations/-/blob/develop/art/new_logo_round.png

**Comment by Ri0n** [comment]
Is there svg version as well?

**Comment by genofire** [comment]
sadly only the legacy one - but thats also okay:
https://dev.sum7.eu/sum7/Conversations/-/blob/develop/art/ic_launcher.svg
