### ISSUE TITLE
Update XMPP logo with last perfect version

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#530]
There was a problem in the XMPP logo:
- https://github.com/psi-im/psi/blob/master/iconsets/system/default/xmpp.svg

-> https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

Can you replace by the good (without XMPP text):
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Linked to:
- https://github.com/psi-im/psi/issues/370

**Comment by Ri0n** [comment]
done
