### ISSUE TITLE
"Message length" and "XMPP account name" are missing in MUC Room tab near subject

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#536]
Please re-add because it is is missing in MUC Room tab near subject:
- Message length 
- XMPP account name

If you want to disable it, please add an option to add it, people want it.

**Comment by tehnick** [comment]
No.

**Comment by Neustradamus** [comment]
Can you export the code in a patch?

Thanks in advance.

**Comment by Neustradamus** [comment]
@tehnick: Can you re-open this ticket?

Users have a problem with this, lost, impossible to know with a quick look in tabs like before, downgrade of Psi is needed...
