### ISSUE TITLE
Default window sizes are too small for some windows (not complete windows)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#545]
Default window sizes are too small for some windows (not complete windows)

Advanced options:
- https://i.ibb.co/cYgQJd8/psi-default-window-size-advanced-problem.png

Toolbars options:
- https://i.ibb.co/yp4TtYY/psi-default-window-size-toolbars-problem.png

Popups options:
- https://i.ibb.co/Lhp0xT7/psi-default-window-size-popups-problem-1.png
- https://i.ibb.co/Wzwx852/psi-default-window-size-popups-problem-2.png
- https://i.ibb.co/tKjDy99/psi-default-window-size-popups-problem-3.png

Status options:
- https://i.ibb.co/xYbNGMt/psi-default-window-size-status-problem-1.png
- https://i.ibb.co/0stFKtK/psi-default-window-size-status-problem-2.png
- https://i.ibb.co/rMk2136/psi-default-window-size-status-problem-3.png

**Comment by tehnick** [comment]
Default size of Options Dialog will be perfect if first tab is shown without any issues.

Some tabs in this dialog may be enormous and and if we ajust default size to them we will receive huge dialog which fills up almost full screen... And it is unacceptable! Users may resize Options Dialog any time when they open such tabs. But they **do not** open **these** tabs **each time** when they open Options Dialog.

**Comment by Neustradamus** [comment]
Texts or parts are not complete, have you looked?

Not beautiful...

Better to have a good window size for options.

-> fixed "width" to increase

A little for : https://i.ibb.co/cYgQJd8/psi-default-window-size-advanced-problem.png

Add and delete buttons + scrollbar + borders
- https://i.ibb.co/yp4TtYY/psi-default-window-size-toolbars-problem.png

Selected presets part is incomplete:
- https://i.ibb.co/xYbNGMt/psi-default-window-size-status-problem-1.png

Border are not complete:
- https://i.ibb.co/Lhp0xT7/psi-default-window-size-popups-problem-1.png
- https://i.ibb.co/Wzwx852/psi-default-window-size-popups-problem-2.png
- https://i.ibb.co/tKjDy99/psi-default-window-size-popups-problem-3.png
- https://i.ibb.co/0stFKtK/psi-default-window-size-status-problem-2.png
- https://i.ibb.co/rMk2136/psi-default-window-size-status-problem-3.png

The "width"  window size must be taken with Status window for be perfect.

Thanks in advance.

**Comment by tehnick** [comment]
5c6dc27b8df1080041b8eaf4c50e08366308c636

**Comment by Neustradamus** [comment]
@tehnick: Thanks, but a little more is missing, look differente languages:
- https://i.ibb.co/GMNLH2q/psi-options-status-window-english.png
- https://i.ibb.co/WBvZ671/psi-options-status-window-russian.png
- https://i.ibb.co/Xjq7NHj/psi-options-status-window-italian.png
- https://i.ibb.co/fHNTCLj/psi-options-status-window-spanish.png
- https://i.ibb.co/4TDp19y/psi-options-status-window-french.png
- https://i.ibb.co/sy3xK5H/psi-options-status-window-swedish.png
- https://i.ibb.co/6bYvYwz/psi-options-status-window-dutch.png

Thanks in advance.

**Comment by tehnick** [comment]
@Neustradamus 
Now the size of Psi Options Dialog is restored after re-opening. And this size depends only on user needs as it should be.

Dialog minimal size will not be limited by tabs content! It is important for users who prefers small size of this window.

**Comment by Neustradamus** [comment]
@tehnick: I think that the base is to have a complete window by default, after if users need to minimize, it is possible...

**Comment by tehnick** [comment]
@Neustradamus 
Huge dialog windows by default is not an option. Humble yourself.
