### ISSUE TITLE
Several Plugin words in the Plugins options

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#546]
Several Plugin words in the Plugins options
- https://i.ibb.co/J7MHG2n/psi-plugins-options-plugin-text.png

Without will be better, we know that it is a plugin list.

**Comment by tehnick** [comment]
Wrong screenshot.

**Comment by Neustradamus** [comment]
@tehnick: Updated, sorry...

**Comment by tehnick** [comment]
> https://i.ibb.co/J7MHG2n/psi-plugins-options-plugin-text.png

It may be fixed now (after unification of plugin names) very easily. I have not looked at code yet, but this should be something easy as this:
```c++
auto pluginName = QString(plugin->name()).replace(" Plugin", "");
```

@Ri0n Do you think this should be really done? Personally I do not see much pros from such change...

**Comment by Ri0n** [comment]
I'm positive on removing. But it's not something important. So if it's not a 5min fix it definitely can wait

**Comment by tehnick** [comment]
And as usual it was not as simple as we thought...

See: 71df7869144f1de43322e2a52c8f650bfcf3436d
