### ISSUE TITLE
Double text in toolbar action names

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#547]
Double text in toolbar action names:
- https://i.ibb.co/JCTDHmr/psi-options-plugins-text-problem.png

**Comment by tehnick** [comment]
7a5479840d2cb4bad633456ea25eb305171ab62a

**Comment by tehnick** [comment]
![Screenshot_20200512_173719](https://user-images.githubusercontent.com/441190/81705447-b7916680-9477-11ea-8c86-1fa7cc163727.png)
