### ISSUE TITLE
"XEP-0184: Message Delivery Receipts" support

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#55]
Dear @psi-im team, @psi-plus team, @Ri0n, @Vitozz, @tehnick,

Can you add "XEP-0184: Message Delivery Receipts" support?
- https://xmpp.org/extensions/xep-0184.html

It is already supported by several projects:
- https://xmpp.org/extensions/#xep-0184-implementations

Thanks in advance.

**Comment by Neustradamus** [comment]
There is a missing part :)
https://github.com/psi-plus/main/issues/674

**Comment by Ri0n** [comment]
Our normal message ui is closing right after send. So it's impossibe to show receipt there.
History is unrelated to this.
