### ISSUE TITLE
"Plugin name": Options -> Settings of "Plugin name"

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#551]
An historical problem:

Can you change in Psi Options -> Plugins
Title of settings of plugins:
- "Plugin name": Options -> Settings of "Plugin name"

We are already in the Psi Options, too heavy.

Thanks in advance.

**Comment by tehnick** [comment]
WONTFIX

**Comment by Neustradamus** [comment]
@tehnick: Why?

**Comment by Neustradamus** [comment]
- https://i.ibb.co/g98314p/psi-options-plugins-example-settings-of-extended-options.png
vs
- https://i.ibb.co/vzMxNwR/psi-options-plugins-example-extended-options-plugins-options.png

Easy, the best is "Settings of PluginName".

**Comment by tehnick** [comment]
@Neustradamus Just stop.
