### ISSUE TITLE
Make options.xml elements sorted

### ISSUE THREAD

**Issue by vthriller** [psi-im/psi#555]
That would greatly help with versioning options in git or just quickly looking for difference between options on different psi installations.

The easiest way would probably be to switch VariantTree from QHash to QMap.

**Comment by tehnick** [comment]
> The easiest way would probably be to switch VariantTree from QHash to QMap.

And get more slow work with options as a result...

**Comment by vthriller** [comment]
> And get more slow work with options as a result...

It's not like there's millions of option reads per minute, so I don't expect that to have much of an impact. But hey, there are people more familiar with this project's internals than I am, that's why I filed an issue instead of a pull request.

**Comment by Ri0n** [comment]
I don't understand the idea behind.
We almost never rearrange options. So it's possible to compare defaults. 
flat mode of the options already has them sorted. I don't think anything has to be done here.

**Comment by Ri0n** [comment]
I just realized there are utils like this https://codebeautify.org/sort-xml-online exists. So this really doesn't worth implementing.
