### ISSUE TITLE
A bad character in Key Storage Diagnostic Text window

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#556]
A bad character in Key Storage Diagnostic Text window:
- https://i.ibb.co/zfR31b1/psi-key-storage-diagnostic-text-bad-character.png

Note: It is not new.

**Comment by tehnick** [comment]
This issue should be redirected to https://github.com/psi-im/qca and marked as MS Windows specific.

**Comment by Neustradamus** [comment]
@tehnick: Can you reopen it and transfer to https://github.com/psi-im/qca?

**Comment by Neustradamus** [comment]
@Ri0n: Can you reopen it and transfer to https://github.com/psi-im/qca?

**Comment by Neustradamus** [comment]
@tehnick: Same problem for GnuPG info window (Psi -> Options -> Plugins -> Settings of OpenPGP -> Own Keys -> Select Key... -> Diagnostics):
- https://i.ibb.co/kJf99nV/psi-openpgp-gnupg-info.png

**Comment by tehnick** [comment]
> Same problem for "GnuPG info" window:

Ok. This may be fixed in plugin.
https://github.com/psi-im/plugins/issues/79

**Comment by Neustradamus** [comment]
@tehnick: And for "Key Storage Diagnostic Text"?

**Comment by tehnick** [comment]
> And for "Key Storage Diagnostic Text"?

This bug is in qca. Report there.

**Comment by Neustradamus** [comment]
@tehnick: No problem in Wime (Text is in English):
- https://i.ibb.co/4W38hrM/psi-vs-wime-key-storage-diagnostic-text-and-security-plugins-diagnostic-text-windows.png

**Comment by tehnick** [comment]
I have no idea which version of QCA they use in their builds.

**Comment by Neustradamus** [comment]
@tehnick: I am not sure, this ticket is now solved too?
