### ISSUE TITLE
About plugin window is empty if the plugin is not enabled

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#558]
Options -> Plugins -> Plugin info button -> About plugin window is empty if the plugin is not enabled

**Comment by tehnick** [comment]
Yes, @Ri0n have not finished new method of loading plugin information. We even have not decided where and how to store plugin's description. New json files do not fit for this. For example, they cannot handle such cases: [openpgpplugin.cpp#L109](https://github.com/psi-im/plugins/blob/599dc1b7/generic/openpgpplugin/src/openpgpplugin.cpp#L109)

Small clarification: this affects only versions 1.4.1236 and newer.

**Comment by Ri0n** [comment]
it's not empty anymore

**Comment by Neustradamus** [comment]
@Ri0n, @tehnick: Thanks, it has been solved but what is the commit?
