### ISSUE TITLE
Message windows sometimes start double spacing after long messages

### ISSUE THREAD

**Issue by RestfulMonad** [psi-im/psi#56]
It seems that once a chat message is sent that's above some maximum character size/line width all further messages have extra line breaks in them. Resizing the window has no effect on the spacing - it seems that there are extra line breaks present?

Here's an example:
[00:00:00] &lt;User 1> a message
[00:00:00] &lt;User 2> another message
[00:00:00] &lt;User 1> a very long message lorem ipsum sit dolor amet lorem ipsum sit dolor amet

[00:00:00] &lt;User 1> a message

[00:00:00] &lt;User 2> another message

Repro steps:
- send a series of short messages followed by a long one

Expected:
- the long message wraps and messages are further messages resume normal spacing

Observed:
- all further messages contain extra line breaks

Windows 8
Psi v0.15
GTalk accounts used for both sending and receiving

**Comment by welshjf** [comment]
Not fixed in the latest release.
