### ISSUE TITLE
Settings of Plugin buttons are not in button actions toolbar options

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#561]
Can you add Settings of Plugin buttons in button actions toolbar options?

**Comment by tehnick** [comment]
wontfix

**Comment by Neustradamus** [comment]
@Ri0n said me a long time ago, it will be possible in future.

The configutation buttons from Plugins can be added in actions list.

**Comment by Ri0n** [comment]
I'm sorry, the description of this tasks says nothing to me.
Probably I commented on something else.
I agree with wontfix for now.

**Comment by tehnick** [comment]
@Neustradamus 
All settings should be in one place: in **settings**! What you want would be very ugly and against all good practices of building UI.

@Ri0n
He wants to add special item "Plugin options" in menu of **each** plugin button on toolbar. And this menu item should call "Plugin options" dialog directly, by-passing the main Psi Options dialog...

**Comment by Neustradamus** [comment]
Yes it is for have like "Options" button

Currently we must to do:
- Psi -> Options -> Plugins -> Settings of Plugin...

In Toolbar, we have already Plugin actions (example: OMEMO/OTR/...).

Settings can be added too...
