### ISSUE TITLE
Plugins buttons missed on groupchat toolbars

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#566]
OMEMO and Conference Logger icons are not in MUC Room / it is in groupchat current actions in "Toolbars" options

Note: I have not looked other plugins.

**Comment by tehnick** [comment]
> Plugins buttons missed on groupchat toolbars

They are missed only on real toolbars, but available in Toolbars tab of Psi Options dialog.

**Comment by Neustradamus** [comment]
@tehnick: Yes, it is specified in publication :)

**Comment by tehnick** [comment]
c63dcda25f4ef484640d9712d60f38e87f0bf0cd

**Comment by Neustradamus** [comment]
@tehnick: Thanks!
