### ISSUE TITLE
Settings of Plugin window is now too small

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#567]
Settings of Plugin window is now too small!

Examples:
- Extended Options
- Conference Logger
- OMEMO
- Stop Spam

I have not looked all.

**Comment by tehnick** [comment]
Just change the size of Plugin Options Dialog. Now its size is restored after re-opening.

**Comment by Neustradamus** [comment]
@tehnick: I think that the base is to have a complete window by default, after if users need to minimize, it is possible...

**Comment by tehnick** [comment]
Huge dialog windows by default is not an option. Humble yourself.
