### ISSUE TITLE
XEP-0334: Message Processing Hints

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#573]
Can you add the XEP-0334: Message Processing Hints support?
- https://xmpp.org/extensions/xep-0334.html

PS: I think that there is but it is not announced in "supported XEP list".

**Comment by Ri0n** [comment]
We already use them where necessary

**Comment by Neustradamus** [comment]
@Ri0n: I know yes but the XEP-0334 is fully supported?
- https://github.com/psi-im/iris/search?q=xep-0334&unscoped_q=xep-0334

Time to add XEP-0334 version number in a doc?

It will be easy to update after it :)

**Comment by Neustradamus** [comment]
@Ri0n: I know yes but it is not detected...
The XEP-0334 is fully supported?
- https://github.com/psi-im/iris/search?q=xep-0334&unscoped_q=xep-0334

Time to add XEP-0334 version number in a doc?

It will be easy to update after it :)

**Comment by Ri0n** [comment]
Please stop or I'll ban you. Everything is already in the doc for a long time. the xep is fully supported on parsing and sending stage.
Other code uses it when necessary.

If you want to ask question ask them in our groupchat. Don't create new useless issues.
