### ISSUE TITLE
XEP-0300: Use of Cryptographic Hash Functions in XMPP

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#574]
Can you add the XEP-0300: Use of Cryptographic Hash Functions in XMPP support?
- https://xmpp.org/extensions/xep-0300.html

PS: I think that there is (complete?) but it is not announced in "supported XEP list".

**Comment by Neustradamus** [comment]
@Ri0n: You have closed, no problem but it is not detected...
Look .features bot function, I have verified today.

Time to add XEP-0300 version number in a doc?

It will be easy to update after it :)

This XEP is linked to:
- XEP-0414: Cryptographic Hash Function Recommendations for XMPP: https://xmpp.org/extensions/xep-0414.html

**Comment by Ri0n** [comment]
bot showed you all the supported hashes. What else do you want?

**Comment by Neustradamus3** [comment]
@Ri0n: XEP-0300/XEP-0414 in the list like some others.

**Comment by Ri0n** [comment]
call this disco features otherwise I don't understand what list are you talking about.
Just added "urn:xmpp:hashes:2" to the list of published features. hashes themselves were already there.
Nothing more to be done for this issue
