### ISSUE TITLE
XEP-0092: Software Version

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#581]
Can you add XEP-0092: Software Version support?
- https://xmpp.org/extensions/xep-0092.html

PS: I think that there is (complete?) but it is not announced in "supported XEP list".

**Comment by Ri0n** [comment]
you probably looked at a wrong support xep list page.
Many of your created issues related xeps implementation are already implemented and declared on the page.
So basically it's a lot of garbage.

**Comment by Neustradamus** [comment]
@Ri0n: Thanks for your reply but it is not detected...
Look .features bot function, I have verified today.

Time to add XEP-0092 version number in a doc?

It will be easy to update after it :)
