### ISSUE TITLE
Add DOAP (Description of a Project) file

### ISSUE THREAD

**Issue by wurstsalat3000** [psi-im/psi#595]
In addition to `psi.appdata.xml`, PSI could provide a DOAP (Description of a Project) file listing [supported XEPs](https://github.com/psi-im/psi/wiki/Supported-XEPs) and their state of implementation (partial/complete, supported version). DOAP, since it’s XML, can easily be parsed and used elsewhere. Examples include: XEP listing on websites, XEP documents mentioning compatible clients, automatic compliance badge calculator, ...).

See https://github.com/pulkomandy/xmpp-doap for implementation ideas. Some examples of usage in the wild:

* https://github.com/dino/dino/blob/master/dino.doap
* https://github.com/yaxim-org/yaxim/blob/master/base.rdf.xml
* https://dev.gajim.org/gajim/gajim/-/blob/master/data/gajim.doap (https://gajim.org/support/extensions/ <- generated automatically)

**Comment by Neustradamus** [comment]
After the Psi ticket which has been solved in part, supported XEP version is missing for a majority:
- https://github.com/psi-im/psi/issues/715

There is a ticket for Psi+:
- https://github.com/psi-plus/main/issues/806

There is a ticket for Iris:
- https://github.com/psi-im/iris/issues/72
