### ISSUE TITLE
Debian: Psi is not really here like other XMPP clients

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#612]
Hello the team,

It is not new but the time is here to do, we are in 2021.

Can you create all Psi packages into the Debian XMPP Maintainer (https://salsa.debian.org/xmpp-team)?
You can create a group like it has been done by the Debian VoIP Packaging Team (https://salsa.debian.org/pkg-voip-team) for Linphone.

Like other projects, for example Gajim have several packages directly without a group.

Another example with ejabberd and the Ejabberd Packaging Team, all sub-projects are in.

The goal is to:
- have new users
- easy installation
- plugins
- security
- easy updates

Currently all Debian/Ubuntu users have Gajim.

Thanks in advance.

**Comment by tehnick** [comment]
This is not the place for discussion of Debian packaging.

**Comment by Neustradamus** [comment]
@tehnick, @Ri0n: Where is the good place?

cc @jannic.

**Comment by Neustradamus** [comment]
Repositories:
- psi
- libpsi
- iris
- qconf
- plugins
- psimedia
- qca
- psi-l10n
- contentdownloader
- resources
- jdns
- qhttp
- libidn
