### ISSUE TITLE
Is there a way to not forcing psi to create one chat per contact no matter what jabber client is used in a conversation?

### ISSUE THREAD

**Issue by morfikov** [psi-im/psi#618]
I'm not sure whether it's a bug or a feature but judging by other jabber clients (like gajim/pidgin/conversations) the behavior I see in psi/psi+ is different and weird.

People usually use multiple devices to write messages with their contacts. I can start a jabber conversation from my phone using the Conversations app, and then switch to a desktop jabber client and continue to write messages. If I had both clients running at the same time, I would see my messages (and those from the contact I write with) in both clients. That's the behavior I see with the jabber clients I use. But Psi/Psi+ is different and it looks like it treats every client as a separate chat. In this way my messages sent from Psi/Psi+ wont be shown in my other jabber clients, which are active at the same time. It's a little bit inconvenient because the messages from my contacts (who usually use the conversations app or different jabber client than psi) will be shown in all the jabber client I use, and in this way the message history will contain only the messages from my contact. So I have a question -- is there an option that wouldn't force psi to create multiple chats per contact when many jabber clients are participating in the conversation?

*OS:* Debian Linux (sid)

*Psi Version:* 1.5+dfsg1-1

**Comment by tehnick** [comment]
Just enable autojid feature.

**Comment by tehnick** [comment]
For example, here:
![Screenshot_20210330_104819](https://user-images.githubusercontent.com/441190/112953203-f7bc0f00-9145-11eb-9cd6-30c82c95b916.png)

**Comment by morfikov** [comment]
If the icon should be blue, it is, and it was I think by default. But switching it on/off doesn't really help. Still m messages generated from psi don't show up in my other clients.

**Comment by morfikov** [comment]
It looks like when gpg encryption is enabled, it doesn't work no matter whether autojid is enabled or not. The same private key is configured in all jabber clients. When my other clients send gpg encrypted message, it can be shown and decrypted in psi. But it doesn't work in the opposite direction.

**Comment by tehnick** [comment]
> But it doesn't work in the opposite direction, I mean it's not shown in other clients

Message Carbons are disabled for openpgp encrypted messages for security reasons.

> The same private key is configured in all jabber clients.

This is a insecure configuration.

**Comment by tehnick** [comment]
> Still m messages generated from psi don't show up in my other clients.

And this is another question, not related to question from description:

>  is there an option that wouldn't force psi to create multiple chats per contact when many jabber clients are participating in the conversation?

**Comment by morfikov** [comment]
Everything works well when gpg isn't used. 

Having the same key configured on multiple clients is secure. Basically I use FDE based on LUKS and no one is able to get the private key. Besides, the key is guarded by a password, so everything is as it should be. I have a separate key for jabber, and for instance for signing commits here on github. If I had multiple keys for each jabber client I use, it would be less secure. Basically other clients don't have issues when the same key is used. So far I see the behavior only in psi. So there's a question -- is there a way to enable this  "IIRC Message Carbons" for gpg as well? Maybe not as a default but as an option left to decide if a user wants this kind of a setup.

**Comment by morfikov** [comment]
> Note: Use of the private mechanism might lead to partial conversations on other devices.

And this is what I experience on my devices when psi is involved. So at least I know what's going on now, but I think there's no other way but switching to other jabber client. Many years ago I was just using one jabber client, but today I have usually two or three devices and having partial conversations on each of them isn't really what I look for or need. :) 

Thanks for the information, and I think this can be closed.

**Comment by tehnick** [comment]
BTW, XEP-0027 is extremely outdated and XEP-0374 should be implemented instead...

**Comment by morfikov** [comment]
I was trying both otr and omemo and they both had issues with decrypting messages. I tried many times to use either one, and that's why I ended up using good old gpg. :)
