### ISSUE TITLE
conferences join

### ISSUE THREAD

**Issue by quiricada** [psi-im/psi#620]
am trying psi+ with ejabberd muc
i have muc room set up with persistence

when i start psi+ and login (goes online), i can join groupchat with the muc room

when i quit psi+ and login again, the roster panel shows the users online, however, the conferences does not show up, i have to manually join the groupchat muc room again.

having to manually join the groupchat every time i log in, is this:
1) as intended,
2) a bug
3) something in the options settings? i've looked through the options settings and i can't find anything relating to this feature.

thanks

**Comment by Vitozz** [comment]
As a solution you can add conference to bookmarks and enable auto-join for this conference
