### ISSUE TITLE
KukuRuzo build installer dll problem

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#628]
@Vitozz build installer dll problem:
- Tested with x64 build: https://sourceforge.net/projects/psiplus/files/Windows/Personal-Builds/KukuRuzo/

Note: Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.28.29914 has been installed.

MSVCR100.DLL is missing:
- https://i.ibb.co/QXbLCFz/msvcr110-dll-is-missing.png

**Comment by Vitozz** [comment]
You have to install redistributable package provided by installer. If it was already installed check you antivirus logs probably your antivirus for some reason delete this library

**Comment by Vitozz** [comment]
Btw if you read Readme.txt 

> Those versions of Psi+ are not official!!!
> 
> About all bugs related to these versions, please report only
> to the developers conference:
> 
> psi-dev@conference.jabber.ru

**Comment by Neustradamus** [comment]
@Vitozz: Like I have said in the ticket, the "Microsoft Visual C++ 2015-2019 Redistribuable (x64) - 14.28.29914 has been installed" with your installer.

The error is here, there is a problem.

**Comment by Vitozz** [comment]
https://www.partitionwizard.com/disk-recovery/msvcr100-dll-missing.html

**Comment by Neustradamus** [comment]
@Vitozz: MSVCR100.dll is into Visual C++ Redistributable Package 2010.

Can you add into your x86 and x64 packages or update your code?

@tehnick: Can you create new builds?

**Comment by Vitozz** [comment]
Fixed since 1549 revision. For older versions download an install redist executabe from the official microsoft site
