### ISSUE TITLE
[OMEMO] Unable to build any sessions, the message was not sent

### ISSUE THREAD

**Issue by Asquator** [psi-im/psi#630]
When OMEMO plugin is enabled, I'm not able to use another type of encryption or not use it at all. 
If I try to send message with OTR/OpenPGP encryption, I get the following notification: 
`[OMEMO] Unable to build any sessions, the message was not sent`
Disabling OMEMO plugin solves the problem and makes possible to send messages again.

*OS:*
Manjaro Linux x86_64
*Psi+ Version:*
v1.5.1515, v1.5.1543-1

![omemoBug](https://user-images.githubusercontent.com/92979391/138428744-d9d59db3-0a6e-4ce3-8b5b-d1e0f9875d28.png)

**Comment by Neustradamus** [comment]
Note: In the main ticket, I have specified that the problem is same with a roster contact in a no-anonymous MUC Room and 1:1 PM messages disabled.

**Comment by Neustradamus** [comment]
@tehnick: For example, I have the problem with @guusdk.

And I have tested with the MUC Room open_chat@conference.igniterealtime.org which have "Role that May Discover Real JIDs of Occupants : Anyone", I have the "*** [OMEMO] Unable to build any sessions, the message was not sent" and the test message is not sent.

@guus has changed few minutes the MUC Room configuration to have "Role that May Discover Real JIDs of Occupants : Moderator", my test message is sent, and I received the good XML error.
