### ISSUE TITLE
Historical Service Discovery problem, an unlimited loop

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#632]
There is a problem historical in Service Discovery, an unlimited loop:
- https://i.ibb.co/2kkmtPt/211104-psi-bug-service-discovery-problem-1.png
- https://i.ibb.co/fpdctxr/211104-psi-bug-service-discovery-problem-2.png

Can you solve it?

Linked to:
- https://github.com/psi-im/psi/issues/632
- https://github.com/psi-im/psi/issues/674
- https://github.com/psi-im/psi/issues/707

**Comment by Ri0n** [comment]
fixed

**Comment by Neustradamus** [comment]
Linked commit:
- https://github.com/psi-im/psi/commit/9f3811bd1bd4a527944e8922970dba856f97163a

**Comment by Neustradamus** [comment]
Thanks to @Ri0n, another commit here:
- https://github.com/psi-im/psi/commit/5ba075a15b9dfc3b6687295b63b5eb7b18512e80

Psi+ 1.5.1873:
- https://github.com/psi-plus/psi-plus-snapshots/commit/6715a1bed5a042d8bbb6fa0f6ae4edeb154bc6b6
