### ISSUE TITLE
Not "updated" .ui files

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#654]
Files:
src\accountadd.ui
src\addurl.ui
src\disco.ui
src\mood.ui
src\options\opt_appearance_misc.ui
src\options\opt_iconset_emo.ui
src\privacy\privacyrule.ui
src\profileopen.ui
src\voicecall.ui

Other files are good, example:
src\about.ui

**Comment by Ri0n** [comment]
this issue doesn't make sense to me

**Comment by Neustradamus** [comment]
@Ri0n: Can you reopen, there are not up-to-date files.

Good files are:
psi\3rdparty\qite\mainwindow.ui
psi\iconsets\system\default\topic.svg
psi\linux\psi-plus.appdata.xml
psi\linux\psi.appdata.xml
psi\mac\Info.plist.in
psi\src\about.ui
psi\src\accountmanage.ui
psi\src\accountmodify.ui
psi\src\accountremove.ui
psi\src\adduser.ui
psi\src\ahcformdlg.ui
psi\src\ahcommanddlg.ui
psi\src\AutoUpdater\guitest\testapp\Info.plist
psi\src\avcall\call.ui
psi\src\bookmarkmanage.ui
psi\src\captchadlg.ui
psi\src\Certificates\CertificateDisplay.ui
psi\src\changepw.ui
psi\src\chatdlg.ui
psi\src\contactmanager\contactmanagerdlg.ui
psi\src\filesharedlg.ui
psi\src\filetrans.ui
psi\src\geolocation.ui
psi\src\groupchatdlg.ui
psi\src\groupchattopicaddlang.ui
psi\src\groupchattopicdlg.ui
psi\src\history.ui
psi\src\info.ui
psi\src\infodlg.ui
psi\src\mucconfig.ui
psi\src\mucinfo.ui
psi\src\mucjoin.ui
psi\src\multifiletransferdlg.ui
psi\src\options\opt_advanced.ui
psi\src\options\opt_appearance.ui
psi\src\options\opt_application.ui
psi\src\options\opt_chat.ui
psi\src\options\opt_events.ui
psi\src\options\opt_general_groupchat.ui
psi\src\options\opt_iconset_activity.ui
psi\src\options\opt_iconset_affiliation.ui
psi\src\options\opt_iconset_client.ui
psi\src\options\opt_iconset_mood.ui
psi\src\options\opt_input.ui
psi\src\options\opt_lookfeel_toolbars.ui
psi\src\options\opt_messages_common.ui
psi\src\options\opt_plugins.ui
psi\src\options\opt_popups.ui
psi\src\options\opt_roster_main.ui
psi\src\options\opt_roster_muc.ui
psi\src\options\opt_sound.ui
psi\src\options\opt_statusauto.ui
psi\src\options\opt_statusgeneral.ui
psi\src\options\opt_statuspep.ui
psi\src\options\opt_theme.ui
psi\src\options\plugininfodialog.ui
psi\src\options\ui_isdetails.ui
psi\src\options\ui_options.ui
psi\src\pgpkey.ui
psi\src\privacy\privacy.ui
psi\src\profilemanage.ui
psi\src\profilenew.ui
psi\src\proxy.ui
psi\src\rosteravatarframe.ui
psi\src\search.ui
psi\src\sendbuttontemplateseditor.ui
psi\src\widgets\fancypopup.ui

Bad files are:
psi\src\accountadd.ui
psi\src\addurl.ui
psi\src\disco.ui
psi\src\mood.ui
psi\src\options\opt_appearance_misc.ui
psi\src\options\opt_iconset_emo.ui
psi\src\privacy\privacyrule.ui
psi\src\profileopen.ui
psi\src\voicecall.ui

**Comment by Ri0n** [comment]
no. This issues describe nothing in particular. It's invalid

**Comment by Neustradamus** [comment]
The format is old.
