### ISSUE TITLE
Avatar problem: Icon and text on it, instead next door

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#675]
There are problems with Avatar and other parts: "Username", "Mood", "Activity", "Geolocalisation", "Status icon" are on the Avatar, it must not.

No problem with: "Using", "Role", "Affiliation", "Last Status", "Status Message", "Time".

All parts must be move at right, please look on screenshots.

Note: Some Avatar has not problem.

Screenshots:

1/ In Contact Tooltips:
- https://i.ibb.co/86B2bm1/psi-icon-text-on-avatar-tooltip-contact-1.png
- https://i.ibb.co/dbLwtxw/psi-icon-text-on-avatar-tooltip-contact-2.png
- https://i.ibb.co/F8hyygJ/psi-icon-text-on-avatar-tooltip-contact-3.png
- https://i.ibb.co/j88dM7n/psi-icon-text-on-avatar-tooltip-contact-4.png
- https://i.ibb.co/T8Cn6cs/psi-icon-text-on-avatar-tooltip-contact-5.png
- https://i.ibb.co/1LdhYRn/psi-icon-text-on-avatar-tooltip-contact-6.png
- https://i.ibb.co/Msn48YD/psi-icon-text-on-avatar-tooltip-contact-7.png

2/ In Contact Status vCards:
- https://i.ibb.co/Zm90ZXr/psi-icon-text-on-avatar-status-vcard-contact-1.png
- https://i.ibb.co/f96sNr5/psi-icon-text-on-avatar-status-vcard-contact-2.png

3/ In MUC Tooltips:
- https://i.ibb.co/ftsWNkK/psi-icon-text-on-avatar-tooltip-muc-room.png

4/ In MUC Status vCards:
- https://i.ibb.co/svz4nGV/psi-icon-text-on-avatar-status-vcard-muc.png

5/ In MUC User Tooltips:
- https://i.ibb.co/QFxRfP8/psi-icon-text-on-avatar-tooltip-muc-user.png

**Comment by snilek** [comment]
I had this same issue with Psi+ 1.4.1456 from Debian repositories.

After I installed the nightly build from https://psi-plus.com/wiki/en:debian#nightly_builds the issue is gone (fixed).

**Comment by Neustradamus** [comment]
@snilek: I have the problem with Psi+ 1.5.1605 (normal) from KukuRuzo on Windows x64:
- https://sourceforge.net/projects/psiplus/files/Windows/Personal-Builds/KukuRuzo/

cc: @Vitozz.

**Comment by Vitozz** [comment]
Like Rion said, it's a Qt5 bug.  The developer no longer supports the 5th version of Qt, especially in Windows.  Therefore, this bug will not be fixed, unfortunately.  Our project has neither the ability nor the desire to fix Qt bugs, as well as subsequent support.

**Comment by Neustradamus** [comment]
@Vitozz: There is Qt 5.15.8 Open Source :)
- https://lists.qt-project.org/pipermail/announce/2023-January/000388.html

Can you update it?

**Comment by Neustradamus** [comment]
@psi-im / @psi-plus devs, @Vitozz, @tehnick, @Ri0n and all others: There is Qt 5.15.9 Open Source :)
- https://lists.qt-project.org/pipermail/announce/2023-April/000406.html

Time to update the old Qt version?

**Comment by Vitozz** [comment]
![изображение](https://user-images.githubusercontent.com/880904/230715061-44558afd-358f-493d-a04e-7ef17d5170bb.png)
As you can see, there are no official Qt versions newer than 5.15.2 and never will be, they are available only on a commercial basis. Yes, new versions of libraries are released as open source, but there are no ready-to-use compiled libraries from the official developer. Of course, you can compile the libraries by yourself. New Qt versions are available in binary builds built using cross-compilation, but there is no webengine support. In order for webengine to be supported, you need to compile Qt using Microsoft Visual Studio. I have neither the time nor the desire to do this in my builds.

**Comment by Neustradamus** [comment]
@Vitozz: Can you create a ticket to explain the problem on https://bugreports.qt.io/?

It is here:
- https://download.qt.io/official_releases/qt/5.15/
- https://download.qt.io/official_releases/qt/5.15/5.15.9/
- https://download.qt.io/official_releases/qt/5.15/5.15.9/submodules/
- https://download.qt.io/official_releases/qt/5.15/5.15.9/single/

For Qt WebEngine:
- https://github.com/qt/qtwebengine/tags
- https://github.com/qt/qtwebengine/releases/tag/v5.15.9-lts-lgpl

But I see only 5.15.2 here:
- https://www.qt.io/offline-installers

**Comment by Neustradamus** [comment]
5.15.11 OpenSource: https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.11/release-note.md

**Comment by Neustradamus** [comment]
@psi-im and @psi-plus teams: It is possible to update Qt?

Qt 5.15.11 is open-source (2023-10-05):
- https://lists.qt-project.org/pipermail/announce/2023-October/000450.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.11/release-note.md

6.2.6 is open-source (2023-09-27):
- https://lists.qt-project.org/pipermail/announce/2023-September/000446.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.6/release-note.md

Do not forget security patches:
- https://download.qt.io/archive/qt/5.15/
- https://download.qt.io/archive/qt/6.2/

Security link: https://www.cvedetails.com/vulnerability-list/vendor_id-6363/QT.html

5.15.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.10/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.8/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.7/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.6/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.2/release-note.md

6.2.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.2/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.1/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md

All git log:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/log/

**Comment by Neustradamus** [comment]
@Ri0n: Thanks!

Merged commit:
- https://github.com/psi-im/psi/commit/a7b19dc6e1bce2b17069eb67cab566957e92a512
