### ISSUE TITLE
Hope for native support for Apple chips

### ISSUE THREAD

**Issue by ghost** [psi-im/psi#697]
Hello,
thank you all for your work

Does Psi have plans to support Apple chips?

**Comment by Ri0n** [comment]
hello,
We probably just need to figure out if any free CI/CD system supports those.
But AFAIK none of developers has Mac

**Comment by stigger** [comment]
CI/CD should not be a problem, the problem is that arm64 support for Qt5 was introduced only since Qt 5.15.9, which is available only commercially at the moment. It is planned to be opensourced on April 5th.

**Comment by Neustradamus** [comment]
@stigger: https://lists.qt-project.org/pipermail/announce/2023-April/000406.html :)

**Comment by stigger** [comment]
> The Qt WebEngine and Qt PDF modules are not supported

I guess we'll have to wait for 5.15.10 and see if the WebEngine is buildable there.

**Comment by Neustradamus** [comment]
@stigger: https://github.com/qt/qtwebengine/releases/tag/v5.15.9-lts-lgpl

And other branches:
- https://github.com/qt/qtwebengine/commits/5.15.10
- https://github.com/qt/qtwebengine/tree/5.15.10
- https://github.com/qt/qtwebengine/tree/5.15.11
- https://github.com/qt/qtwebengine/tree/5.15.12
- https://github.com/qt/qtwebengine/tree/5.15.13
- https://github.com/qt/qtwebengine/branches/all

**Comment by stigger** [comment]
@Neustradamus Let me know if you manage to build Qt 5.15.9 for macOS arm64 with QtWebEngine enabled.

**Comment by stigger** [comment]
The sources for Qt 5.15.10 were published in June, and Psi seems to build and work fine with it.

**Comment by Neustradamus** [comment]
Yes!

I hope that the team will create new @psi-im and @psi-plus builds with Qt 5.15.10 and security patches too:
- https://lists.qt-project.org/pipermail/announce/2023-June/000418.html

**Comment by Neustradamus** [comment]
@psi-im and @psi-plus teams: It is possible to update Qt?

Qt 5.15.11 is open-source (2023-10-05):
- https://lists.qt-project.org/pipermail/announce/2023-October/000450.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.11/release-note.md

6.2.6 is open-source (2023-09-27):
- https://lists.qt-project.org/pipermail/announce/2023-September/000446.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.6/release-note.md

Do not forget security patches:
- https://download.qt.io/archive/qt/5.15/
- https://download.qt.io/archive/qt/6.2/

Security link: https://www.cvedetails.com/vulnerability-list/vendor_id-6363/QT.html

5.15.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.10/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.8/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.7/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.6/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.2/release-note.md

6.2.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.2/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.1/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md

All git log:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/log/
