### ISSUE TITLE
Using SQLite

### ISSUE THREAD

**Issue by pokonski** [psi-im/psi#7]
Hello

I am getting close to having some time to work on Psi so decided to start this issue to discuss transition to SQLite. 

Main question is: what do we want to store in the database?  Do we store everything there is (including roster cache) or just message history?

**Comment by Ri0n** [comment]
The patch is merged to upstream.
Let's open more specific issues if anything else has to be ported to sqlite.
For now I'm Ok with xml for settings and don't see a reason to port it.
