### ISSUE TITLE
don't require presence signatures to use OpenPGP

### ISSUE THREAD

**Issue by jkarneges** [psi-im/psi#70]
Probably we should think about how to do this better. One issue is that presence is sort of relied on to discover the key of the other user.

> we are using PSI in our organisation since 2006. We are also using GPG
> with smart cards for eMail. But it is impossible to use PSI with
> GPG/PGP in a commercial organisation like us.
> 
> The reason is that PSI requires a PGP/GPG signature for the Status on
> each status change.
> 
> This kills PGP in PSI.
> Pleas let me explain why:
> The most important feature for us is to see who is at work and
> available. Before making a phone call our user are using Jabber/PSI to
> schedule and give time for preparation.  If somebody is not on line in
> PSI, everybody expects that this person is not at work and not
> available. Especially because we are located on many different locations.
> 
> The Status signature is killing this main feature. We tried it.
> Every time after a Notebook went to sleep it is creating an error. It
> requires every time manual actions from the user. At least the User
> has to fill in his PIN for the SmartCard. But most time you have to
> make more klicks. First confirm an error, re-connect manually and than
> fill in the PIN.
> How ever. The Result is that many Users are very often off line.
> So we had to disable PGP.
> # REQUEST / PLEASE
> 
> Is it possible to get a version of PSI where the Status signature is
> optional. Is it possible to configure it?
> 
> I am sure many user will use PGP and I think PGP is the best solution
> for chat and Mail. But not as it is implemented in the moment. We will
> immediately change to 100% PGP encryption if the User have the
> possibility.
> A "force PGP/GPG" would also be nice. If PGP/GPG is available the PSI
> client should force the user to use it. Or as an option...  But this
> is not the main issue.

**Comment by tehnick** [comment]
Special option "Do not sign own presence status" is available in OpenPGP plugin version 1.7 and newer: https://github.com/psi-im/plugins/commit/2d5e237d5b7c37301213f1d9f3cfa5a8f374ebf0
https://github.com/psi-im/plugins/blob/master/generic/openpgpplugin/changelog.txt

**Comment by Neustradamus3** [comment]
@tehnick: Nice! :)
