### ISSUE TITLE
Avatar option under account is greyed out

### ISSUE THREAD

**Issue by fuck-shithub** [psi-im/psi#703]
Avatar option under account is greyed out. Why? I want to set an avatar but Psi+ won't let me.

How to reproduce:
1. right click on an account in the roster
2. observe that the option "Avatar" is disabled and greyed out and cannot be accessed at all.

*OS:* Gentoo Linux
*Psi Version:* v1.5.1644

**Comment by Neustradamus** [comment]
@fuck-shithub: Can you publish a screenshot?

**Comment by fuck-shithub** [comment]
Sadly I cannot post a screenshot because X11 does not allow me to use keyboard shortcuts while having a context menu open. Just imagine this:

In the roster I right click on my account, and here are the options in the context menu: Everything in ~~strikethrough~~ is a disabled/greyed out button

Status >
~~Mood~~
~~Activity~~
~~GeoLocation~~
~~Avatar >~~
Groupchats >
---
Add a Contact
Service Discovery
New Blank Message
Contacts Manager
Privacy Lists
---
XML Console
---
Modify Account...
Plugins >
Admin >

**Comment by Ri0n** [comment]
looks like pubsub is disabled on your server

**Comment by fuck-shithub** [comment]
That's weird, because according to https://compliance.conversations.im/server/nuegia.net/ my server supports PEP, which depends on pubsub, right? Why does Psi+ not work with it then?

**Comment by Ri0n** [comment]
That was a bug in psi. Fixed with https://github.com/psi-im/iris/commit/0437105de6e9a544d25f230e30000c18bac0d67c

**Comment by Neustradamus** [comment]
@fuck-shithub: Can you confirm the fix?
