### ISSUE TITLE
XMPP.org client list problem

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#715]
Dear @psi-im, @psi-plus teams, @Ri0n,

There is always a problem with Psi and Psi+ on XMPP.org, no logo showed, no links with XEPs, ...
- https://xmpp.org/software/
- https://xmpp.org/extensions/
- https://xmpp.org/doap/psi.doap
- https://xmpp.org/doap/psiplus.doap

A GitHub search:
- https://github.com/search?q=https%3A%2F%2Flinkmauve.fr%2Fns%2Fxmpp-doap&type=code

Example for Dino:
- https://github.com/dino/dino/blob/master/dino.doap
- https://xmpp.org/doap/dino.doap

Can you solve it?

Thanks in advance.

Linked to:
- https://github.com/psi-im/psi/blob/master/psi.doap

**Comment by Neustradamus** [comment]
@Ri0n: The problem is always here, linked to doap files.

**Comment by Neustradamus** [comment]
@butyoutried, @Ri0n: There is a problem in the file:
```
    <release>
      <Version>
        <revision>0.1.5</revision>
        <created>2020-09-06</created>
        <file-release rdf:resource='https://github.com/psi-im/psi/releases/download/1.5/psi-1.5.tar.xz'/>
      </Version>
    </release>
```

It is 1.5.0 (2020-09-06), the latest one ^^

**Comment by butyoutried** [comment]
> There is a problem in the file:

Thanks, fixed.

**Comment by Neustradamus** [comment]
@butyoutried: Thanks!
- https://github.com/psi-im/psi/pull/757

**Comment by Neustradamus** [comment]
After the Psi ticket which has been solved in part, supported XEP version is missing for a majority:
- https://github.com/psi-im/psi/issues/715

There is a ticket for Psi+:
- https://github.com/psi-plus/main/issues/806

There is a ticket for Iris:
- https://github.com/psi-im/iris/issues/72
