### ISSUE TITLE
Is it possible to retain Qt4 support?

### ISSUE THREAD

**Issue by barracuda156** [psi-im/psi#718]
Some platforms do not have higher versions working. Darwin PPC, for instance.

**Comment by Ri0n** [comment]
Unfortunately impossible. This requires a lot of development not just in Psi but also in its dependencies. really a lot of work.

**Comment by barracuda156** [comment]
Dependencies support Qt4, AFAIK. Or is there something new which was not among dependencies earlier?

**Comment by Ri0n** [comment]
Psi definitely has new stuff, which for example needs new QCA.

**Comment by barracuda156** [comment]
`Qca` 2.2.1 builds with Qt4, I have just done that (fixing PowerPC build along).

**Comment by Ri0n** [comment]
2.2.1 is too old.
Ideally we need to build master branch of our fork https://github.com/psi-im/qca

**Comment by barracuda156** [comment]
Ok, thank you for the info.
