### ISSUE TITLE
Qt update (and with security patches)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#727]
@psi-im and @psi-plus teams: It is possible to update Qt?

Qt 5.15.11 is open-source (2023-10-05):
- https://lists.qt-project.org/pipermail/announce/2023-October/000450.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.11/release-note.md

6.2.6 is open-source (2023-09-27):
- https://lists.qt-project.org/pipermail/announce/2023-September/000446.html
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.6/release-note.md

Do not forget security patches:
- https://download.qt.io/archive/qt/5.15/
- https://download.qt.io/archive/qt/6.2/

Security link: https://www.cvedetails.com/vulnerability-list/vendor_id-6363/QT.html

5.15.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.10/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.8/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.7/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.6/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.2/release-note.md

6.2.x previous:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.5/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.4/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.3/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.2/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.1/release-note.md
- https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md

All git log:
- https://code.qt.io/cgit/qt/qtreleasenotes.git/log/

Linked to:
- https://github.com/psi-plus/main/issues/803

**Comment by Ri0n** [comment]
I guess you are talking about building new Psi release based on the new Qt version

**Comment by Ri0n** [comment]
Psi can now be built with Qt 6.7
