### ISSUE TITLE
XEP-0292: vCard4 Over XMPP

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#759]
Can you add "XEP-0292: vCard4 Over XMPP" support?
- https://xmpp.org/extensions/xep-0292.html

**Comment by Ri0n** [comment]
done.

there are some other avatar issues exist, but unrelated to the implementation.

**Comment by Neustradamus** [comment]
@Ri0n: Good job!

A lot of commits that you have done in Iris and Psi, the latest is:
- https://github.com/psi-im/psi/commit/260a7cb8a819d9688a10368c34a59777dbac8948

Psi+ 1.5.1969:
- https://github.com/psi-plus/psi-plus-snapshots/commit/afde2a2f02d488a2764394ae658569326cf81bdf
