### ISSUE TITLE
XEP-0398: User Avatar to vCard-Based Avatars Conversion

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#760]
Can you add "XEP-0398: User Avatar to vCard-Based Avatars Conversion" support?
- https://xmpp.org/extensions/xep-0398.html

**Comment by Ri0n** [comment]
In general we now try to ignore vcard photo as much as possible.
there is nothing more to support

**Comment by Neustradamus** [comment]
Some commits:
- https://github.com/psi-im/iris/commit/64e9997aa1e9ffebc88bbddf01554e7f69e33b16
- https://github.com/psi-im/psi/commit/71d4904a9f975a617efe79fb3afa5920affa459b
- https://github.com/psi-im/psi/commit/3b0f31e50058e67c8133fa13af95d45287c53ab2
