### ISSUE TITLE
Edit a bookmark is not easy in "Manage Bookmarks"

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#775]
Edit a bookmark is not easy in "Manage Bookmarks" window, there is not an "Edit" button.
We need to use "F2" key but the cursor is here...

To save a change, it is important to click on "OK" and do not close the window normally.

**Comment by Ri0n** [comment]
I completely don't understand your point.
Do you want to replace "Ok" with "Apply" or something like this?
F2? what for...

**Comment by Ri0n** [comment]
double click is the solution :)

**Comment by lao-mang** [comment]
read it. but there is such a possibility     
прочитано. но такая возможность есть

![2024-05-07_16-56-07](https://github.com/psi-im/psi/assets/66281465/e3a67213-17fb-414e-be38-fe7a92107464)

**Comment by Neustradamus** [comment]
@lao-mang: Of course, it works with "Star" button, but not in "Manage Bookmarks", it is for this an "Edit" button will be perfect:
- https://i.ibb.co/ZKXLXKN/psi-manage-bookmarks-button-problems.png

Linked to:
- https://github.com/psi-im/psi/issues/777

**Comment by EOUpSL93Y** [comment]
Пообщались; в общем, перевожу: просто добавьте возможность редактировать существующую закладку в менеджере закладок (на сейчас это можно делать только для новой вроде как). В остальных случаях - надо быть в конфе, тыкать звездочки и все такое. Есть менеджер - просто добавьте одну кнопку там и будет удобнее.

**Comment by lao-mang** [comment]
поддерживаю

**Comment by Neustradamus** [comment]
A solution has been added: The "Name" form has been added in more "Host", "Room", "Nickname", "Password".

**Comment by Neustradamus** [comment]
@Ri0n: The same problem exists in "Psi: Proxy Profiles" window, can you look?
