### ISSUE TITLE
wayland+tabs: unusable. full of gui glitches

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psi#784]
Any chatlog (classic, webkit, engine).
Quite often scrolling on any widget stops working (doesn't rerender contents), or it rerenders just  a part of contents.
Input field renders just first line of pixel basically making input invisible.
coming messages are not visible till manual window resize.
Opening a second tab + window resize with webengine -> crash w/o any good trace.

*OS:* Gentoo 

*Psi Version:* Psi 1.5.1846 (2024-05-08, 39ecbdd9, webengine)

Without tabs all the glitches are gone. Works just great.

**Comment by Ri0n** [comment]
switched to software rendering on linux. works well now.

**Comment by v-fox** [comment]
There is nothing "well" about it. For me, under KDE/wayland, Qt6's RHI acceleration always gets enabled and Psi is unusable. It flashes white when opening chat window, then spams this into console:
```
[20250521 21:15:50] W:VULKAN: No NativePixmap. (unknown:0, unknown)
[20250521 21:15:50] Compositor returned null texture (unknown:0, unknown)
```

Even launching with `QSG_RHI='' QSG_RHI_BACKEND=software` or switching `kcmshell6 kcm_qtquicksettings` doesn't help.

Using same hack as with [goldendict](https://github.com/xiaoyifang/goldendict-ng) works for now: launching with `QT_QUICK_BACKEND=software`.

This needs a proper fix.

**Comment by Vitozz** [comment]
I use Psi (Qt 6.9.0) in Plasma 6 with wayland protocol. But my psi package was compiled with -DUSE_X11=OFF flag and psi works normal. Except for recent webengine update which broke normal work with nvidia video cards (already fixed it, I think).

**Comment by v-fox** [comment]
> I use Psi (Qt 6.9.0) in Plasma 6 with wayland protocol. But my psi package was compiled with -DUSE_X11=OFF flag and psi works normal. Except for recent webengine update which broke normal work with nvidia video cards (already fixed it, I think).

Well, I use @Ri0n's Gentoo overlay.
But I've stumbled on even bigger issue, the one I abandoned psi for gajim in the first place: #816 and #62
So I had to abandon it again, despite workaround to this. [Modern IM](https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_protocols) is suffering…

**Comment by Ri0n** [comment]
I'd recommend using Telegram. it's neat.
