### ISSUE TITLE
Add an outline to the "Psi: Advanced" window

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#792]
Go to Options -> Advanced -> Open detached "Psi: Advanced" window

You can see that the window is not full at beginning and when you maximize the window, you will see that there is not outline and several characters (and checkbox) are little out of screens...

Can you add an "outline" like all other windows to be perfect?

**Comment by yatigautam** [comment]
i would like to solve this issue.

**Comment by Ri0n** [comment]
@yatigautam just make sure, it's possible to apply css to this widget.
we have options.ui.chat.css option, which can stylize any widget in chat dialog. 
If we can apply something 
```
QLabel#lb_ident { border: 1px solid black; }
```
it should be enough.

**Comment by Ri0n** [comment]
if you saw my just deleted message, ignore it. it was about different issue =)

seems like setContentMargins has to be fixed on the top level widget

**Comment by Ri0n** [comment]
actually there is a bunch of issues with this options editor.

- for example double click on boolean fields produces artifacts
- editing multiline values is close to impossible. 
- maps do not have special editor at all.
- some options chould have combobox, but those are just string type
- shortcuts editor is just string based (requires to open another part of options designed special for shortcuts)

@Neustradamus feel free to create tickets for all of these :)

**Comment by Neustradamus** [comment]
@yatigautam: Nice :)
I have not checked my emails before!

To see the problem, please maximize the window and look the text cropped a little ("Checkbox", "Filter", "options...", "Always...", "QString", and "Reset" button for example), there is no a border like other window.

**Comment by Neustradamus** [comment]
@yatigautam: Nice :)
I have not checked my emails before!

To see the problem, please maximize the window and look the cropped text ("Checkbox", "Filter", "options...", "Always...", "QString", and "Reset" button for example), there is no border like other windows.

**Comment by yatigautam** [comment]
ok, i got it. will update you asap.

**Comment by Neustradamus** [comment]
@Ri0n: Thanks, it has been added in commit:
- https://github.com/psi-im/psi/commit/d33895741f930c867cd3331bacf1bbe54e3617bf
