### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by jjrh** [psi-im/psi#804]
Attempting to compile on 127d3e4ef482892faec9b484240817ca0f7db1c8 results in a error. On Ubuntu 23.10, with QT5.

```
psi/src/widgets/taskbarnotifier.cpp:120:52: error: invalid use of incomplete type ‘class QIcon’
  120 |         parent_->setWindowIcon(setImageCountCaption(count)); // qApp->setWindowIcon(setImageCountCaption(count));

```

Adding `#include <QIcon>` to `taskbarnotifier.cpp` fixes the issue.

**Comment by Ri0n** [comment]
thanks!
