### ISSUE TITLE
XEP-0308: Last Message Correction

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#820]
Can you update the "XEP-0308: Last Message Correction" support?
- https://xmpp.org/extensions/xep-0308.html

**Comment by Ri0n** [comment]
looks correct already

**Comment by Neustradamus** [comment]
@rkfg: Can you look the latest XEP-0308 version?
- https://xmpp.org/extensions/xep-0308.html

Linked to:
- https://github.com/psi-im/iris/pull/45

**Comment by Neustradamus** [comment]
Can you look the latest XEP-0308 version? At this time, the latest is:
- https://xmpp.org/extensions/xep-0308.html#revision-history-v1.2.1

Can you edit in the .doap file, what is the version supported?
- https://github.com/psi-im/psi/blob/master/psi.doap

@Ri0n: Please reopen before the verification and the adding version in .doap file.

cc: @rkfg.

**Comment by rkfg** [comment]
Sorry, haven't used XMPP for about 7 years I think 😅

**Comment by Neustradamus** [comment]
@rkfg: Sad news, you must to use again...

@Ri0n has updated the .doap file:
- https://github.com/psi-im/psi/commit/1cfc05235e325dd038f5f641b050bc5396e7d0f3
