### ISSUE TITLE
XEP-0359: Unique and Stable Stanza IDs

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#823]
Can you update "XEP-0359: Unique and Stable Stanza IDs" support?
- https://xmpp.org/extensions/xep-0359.html

**Comment by Ri0n** [comment]
it is implemented long ago

**Comment by Neustradamus** [comment]
Yes not fully supported like other XEPs :/

Can you look XEP-0359 version? At this time, the latest is 0.7.0 (2023-02-20):
- https://xmpp.org/extensions/xep-0359.html#revision-history-v0.7.0

Can you edit in the .doap file, what is the version supported?
- https://github.com/psi-im/psi/blob/master/psi.doap

Linked to:
- https://github.com/psi-im/iris/pull/69

cc @stigger.
