### ISSUE TITLE
XEP-0153: vCard-Based Avatars

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#826]
Can you update "XEP-0153: vCard-Based Avatars" support?
- https://xmpp.org/extensions/xep-0153.html

**Comment by Ri0n** [comment]
Not clear issue description. Closing

**Comment by Neustradamus** [comment]
Can you look XEP-0153 version?
- https://xmpp.org/extensions/xep-0153.html#revision-history-v1.1

Can you edit in the .doap file, what is the version supported?
- https://github.com/psi-im/psi/blob/master/psi.doap

**Comment by Neustradamus** [comment]
@Ri0n has added the latest XEP-0153 version support (1.1.1):
- https://github.com/psi-im/psi/commit/5593ef501473715eddf35ac8850b5c95f8723148
