### ISSUE TITLE
XEP-0380: Explicit Message Encryption

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#827]
Can you update "XEP-0380: Explicit Message Encryption" support?
- https://xmpp.org/extensions/xep-0380.html

Linked to:
- https://github.com/psi-im/iris/commit/59c87816772697c984764779c7565d7e11f0ed88

**Comment by Ri0n** [comment]
checked. doesn't need updates.

**Comment by Neustradamus** [comment]
Can you look XEP version?
- https://xmpp.org/extensions/xep-0380.html#revision-history-v0.4.0

**Comment by Neustradamus** [comment]
Can you look XEP-0380 version?
- https://xmpp.org/extensions/xep-0380.html#revision-history-v0.4.0

Can you edit in the .doap file, what is the version supported?
- https://github.com/psi-im/psi/blob/master/psi.doap

**Comment by Neustradamus** [comment]
@tehnick, @Ri0n: About my request, normally, it is now `urn:xmpp:omemo:1` with libomemo-c?

It is possible to update like my initial request?

**Comment by Neustradamus** [comment]
@Ri0n: Maybe, the Psi project can replace this OMEMO library?

There is Picomemo (done by @mierenhoop):
- https://github.com/mierenhoop/picomemo

It can replaces:
- libomemo-c: https://github.com/dino/libomemo-c and Psi fork: https://github.com/psi-im/libomemo-c
