### ISSUE TITLE
[Tip of the Day] Update hyperlink to jisp.netflint.net

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi#83]
Earlier version
http://web.archive.org/web/20050607014438/http://jisp.netflint.net/

Recent version (lesser preferable)
http://web.archive.org/web/20070405110711/http://jisp.netflint.net/

PsiWiki
http://wayback.archive.org/web/20060101015745/http://psi-im.org/wiki/Iconsets#Contributions

**Comment by GreenLunar** [comment]
Do you want to launch a new website with torrents indexing Jisp files?

**Comment by Ri0n** [comment]
tips of day were removed. too annoying
