### ISSUE TITLE
Add a feature to clean the cache

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#836]
Can you add a feature to clean the cache (one by one and one all in one):
- vCard
- Avatar
- Shared files

On Windows, it is in:
- C:\Users\USERNAME\AppData\Local\Psi+\avatars
- C:\Users\USERNAME\AppData\Local\Psi+\profiles\PROFILENAME\vcard
- C:\Users\USERNAME\AppData\Roaming\Psi+\shares
- C:\Users\USERNAME\AppData\Roaming\Psi+\aesgcm_files

**Comment by Ri0n** [comment]
as was already mentioned it's already in "cleaner" plugin.
I didn't check though.
