### ISSUE TITLE
pgp: complaint about expired signing key, when newer keys could be used

### ISSUE THREAD

**Issue by zougloub** [psi-im/psi#89]
Hi,

This bug is a duplicate of https://code.google.com/p/psi-dev/issues/detail?id=531

Expired keys are not discarded even if there are newer keys available; revoking them doesn't help, but deleting them does work around the problem.
I haven't looked into the problem yet, but yes, it might be a QCA issue.

Encountered with psi-0.15.

**Comment by tehnick** [comment]
OpenPGP encryption in Psi+ does not use GnuPG plugin from QCA anymore.

This issue is fixed in Psi+ for now and will be fixed in next stable release of Psi-2.0.
