### ISSUE TITLE
Service discovery dialog hangs when retrieving information

### ISSUE THREAD

**Issue by ruimaciel** [psi-im/psi#9]
I've noticed that Psi's "service discovery" dialog hangs Psi when retrieving info such as the groupchat list.

It would be nice if psi, or even this dialog alone, didn't hang when retrieving info from the service discovery.

**Comment by Ri0n** [comment]
It's related to huge stanzas receiving and parsing. I agree it's annoying. for example groupchat list on jabber.org will make Psi suffer.
Fortunately we have implemented paged discovery. And with server supporting this things should become better.
There is a window for further improvements as well.

**Comment by Ri0n** [comment]
a few years later...

@liuch me merged everything in Psi. can we close it? :)

**Comment by liuch** [comment]
I don't see any obstacles to this. The code is already in the upstream.

**Comment by Neustradamus** [comment]
The "Service Discovery" works better since the recent @Ri0n commit here:
- https://github.com/psi-im/psi/commit/5ba075a15b9dfc3b6687295b63b5eb7b18512e80

Psi+ 1.5.1873:
- https://github.com/psi-plus/psi-plus-snapshots/commit/6715a1bed5a042d8bbb6fa0f6ae4edeb154bc6b6
